SetReplace.wl
SetReplace.wlt

* Implements SetReplace and related functions in Wolfram Language.
* Implementation is slow, but it can be used to test C++ implementation.
* Implements HypergraphPlot, that plots a set of directed hyperedges (lists) as a Graph with each hyperedge represented as a series of arrows.
* Adds argument checks for all functions.
* Implements unit tests for all functions.
* Evaluate a rule that splits a single edge into two, and plot the results:
`HypergraphPlot[manyEdges = SetReplace[{{0, 1}}, {{a_, b_}} :> Module[{$0}, {{a, $0}, {$0, b}}], 5]]`
* Reduce it back to a single edge:
`SetReplaceFixedPoint[manyEdges, {{a_, b_}, {b_, c_}} :> {{a, c}}]`
* You should see `{{0, 1}}` as output.
* As a more complicated example, try converting a point with 3 connections into a triangle:
`HypergraphPlot[ …

Simple WL implementation of SetReplace

---

SetReplace.wl
SetReplace.wlt

* Closes https://github.com/maxitg/SetReplace/issues/5.
* Implements `FromAnonymousRules` objects, that allows one to easily specify rules operating on anonymous vertices.
* For example, specifying `FromAnonymousRules[{{{1, 2}} -> {{1, 2, 3}}}]` would imply every 2-vertex edges should be extended to a 3-vertex edge, with the last vertex being a newly created one. In this particular case, it will put a `Module` on the right-hand side to accommodate for the new vertex.
* A simple example that grows 3-vertex edges indefinitely:
`HypergraphPlot[SetReplace[{1 -> 2 -> 3, 2 -> 3 -> 4}, FromAnonymousRules[{2 -> 3 -> 4, 1 -> 2 -> 3} -> {3 -> 4 -> 5, 2 -> 3 -> 4, 1 -> 2 -> 3}], 10] /. (a_ -> b_ -> c_) :> {a, b, c}]`
* Generate an interesting-looking network:
`HypergraphPlot[SetReplace[{{0, 1}, {0, …

Anonymous rules

---

.gitignore
PacletInfo.m
SetReplace.wl
build.wls

* Adds a build script that packs a paclet file.
* WolframScript is a required to run the build script.
* `WLUsageString` is a prerequisite, install it from [releases page](https://github.com/maxitg/UsageString/releases).
* Run `wolframscript build.wls` from terminal. This will create `SetReplace-0.1.paclet` file in the same directory as `build.wls` is located.
* Open Mathematica and evaluate ```PacletManager`PacletInstall["path_to_paclet"]```, where `path_to_paclet` is the path to the newly created `SetReplace-0.1.paclet`.
* Evaluate ```PacletManager`PacletInformation["SetReplace"]```, and make sure the output is not an empty list.
* Import the package with ```<<SetReplace` ```
* Try evaluating, for example, `HypergraphPlot @ SetReplace[{{0, 0}}, FromAnonymousRules[{{{1, 2}} -> {{1, 3}, …

Build script

---

SetReplace.wlt
SetReplace/SetReplace/Set.cpp

* Resolves #28.
* Implements numerous unit tests, including 3 suits of random tests for matching isomorphic, distinct and degenerate graphs.
The bug was in the heuristic that decided which rule input try to match next. Specifically, if the input radius was larger than 2, the heuristic would always choose an expression for which no atoms are matched yet, and would that abort the matching attempt because there are now no candidate atoms for matching.
* Verify the bug from #28 is fixed, the following now yields `{}`:
```
SetReplace[{{1, 5}, {2, 1}, {2, 3}, {2, 4}, {2, 5}, {3, 1}, {4, 
2}, {4, 5}}, 
FromAnonymousRules[{{1, 5}, {2, 1}, {2, 3}, {2, 4}, {2, 5}, {3, 
1}, {4, 2}, {4, 5}} -> {}], 1, Method -> "C++"]
```
* Run unit tests, this now uses parallel kernels, and takes awhile, because …

Fix C++ matching of rules with radius over 2

---

SetReplace.wl

* Closes #33.
* Removes dependance on [UsageString](https://github.com/maxitg/UsageString) by copying the relevant code directly into `SetReplace.wl`.
* Uninstall `UsageString` if installed by running `PacletUninstall["UsageString"]`.
* Restart Wolfram kernel.
* Evaluate `?SetReplace` to check that usage strings are still correct.

Remove dependance on UsageString package

---

install.wls

* Implements script that installs the built paclet.
* Only macOS is supported at the moment.
* In Terminal, `cd` to the root repository directory.
* Run `./build.wls` to build the paclet.
* Run `./install.wls` to install the paclet.
* Restart Wolfram Kernel in Mathematica.
* Evaluate ``<<SetReplace` `` to import the package.
* Evaluate `SetReplace[{{0}}, {{x_}} :> {{x}}, Method -> "C++"]`.
* If the paclet is installed correctly, `{{0}}` will be returned and no messages will be produced.

Install script

---

SetReplace.wl
SetReplace.wlt

* Resolves #24.
* Fix a bug that would cause `HypergraphPlot` to fail for large graphs.
* This was happening due to a change in Wolfram Language v12, in which large graphs are no longer plotted by default, and `GraphPlot` must be explicitly called to plot them.
* Add unit tests for large graphs.
* Check example from the issue now works:
```
In[.] := HypergraphPlot[
SetReplace[{{1}}, FromAnonymousRules[{{1}} -> {{2}, {2}, {1, 2}}], 
10000]]
```
* Run unit tests:
```
In[.] := TestReport["path_to_SetReplace.wlt"]
```

Fix HypergraphPlot for large graphs

---

SetReplace.wl
SetReplace.wlt

* Resolves #16.
* `HypergraphPlot` now plots lone vertices as well as edges. Lone vertices may appear if single-vertex edges are present in a graph, i.e., `{{0}}`.
* Vertices that have single-vertex edges are colored differently, note drawing loops would not work because that would be ambiguous with, say, `{{0, 0}}`.
* Add unit tests for these colors.
* Check example from the issue is now evaluated correctly:
```
In[.] := HypergraphPlot[{{0}}]
```
* Compare vertices with different numbers of single-vertex edges:
```
In[.] := HypergraphPlot[{{0, 1, 2, 3}, {1}, {2}, {2}, {3}, {3}, {3}}]
```
* Run unit tests:
```
In[.] := TestReport["path_to_SetReplace.wlt"]
```

HypergraphPlot lone vertices

---

SetReplace.wlt
SetReplace/SetReplace/Set.cpp
SetReplace/SetReplace/Set.hpp
SetReplace/SetReplace/SetReplace.cpp

* Closes #23.
* Allows aborting evaluation of C++ code.
* Abort check is inserted inside the low-level matching code, so it should happen fast in every case.
* Add a unit test.
* The following should finish with `$Aborted` in about 1 second (otherwise it would take 3):
```
In[.] := TimeConstrained[
SetReplace[{{0}}, 
FromAnonymousRules[{{{0}} -> {{0}, {0}, {0}}, {{0}, {0}, {0}} -> \
{{0}}}], 30], 1]
```
```
Out[.] = $Aborted
```
* Try aborting the following interactively:
```
In[.] := SetReplace[{{0}}, 
FromAnonymousRules[{{{0}} -> {{0}, {0}, {0}}, {{0}, {0}, {0}} -> \
{{0}}}], 30]
```
```
Out[.] = $Aborted
```
* Run unit tests
```
In[.] := TestReport["path_to_SetReplace.wlt"]
```

Abort C++ evaluation

---

SetReplace/SetReplace/Set.hpp

* Adds explicit `#include <functional>` to fix compilation error on Linux.
* Run `./build.wls` on Linux, and see compilation is successful.

Add functional include to fix compilation on Linux.

---

SetReplace/SetReplace/Set.cpp
SetReplace/SetReplace/Set.hpp

* Fixes an exception on Windows, which was caused by passing a lambda function that checks for abort in progress by reference.
* On Windows, run,
```
SetReplace[{{0}}, FromAnonymousRules[{{0}} -> {{1}}], Method -> "C++"]
```
* Before, C++ code failed with `LibraryFunctionError`, but now, it should evaluate correctly.

Fix Windows runtime exception

---

SetReplace.wlt

It turns out it is possible for a `TimeConstrained[...]` evaluation to finish earlier than the specified time, at least this happens on Windows.
So, to avoid a failing test because of this, the min time constraint is changed to be below 1 second.
* Evaluate unit tests (especially on Windows):
```
In[.] := TestReport["path_to_SetReplace.wlt"]
```
* Check all tests pass.
* Check if `CPUTimeUsed` in test 49 is smaller than 1 second.

Fix min time in Abort test

---

SetReplace/ToPatternRules.wlt
SetReplace/correctness.wlt
SetReplace/libSetReplace/Match.cpp
SetReplace/setSubstitutionSystem$wl.m

* Closes https://github.com/maxitg/SetReplace/issues/44.
* Changes the evaluation order to, by priority:
* Least recent expressions are updated first. I.e., the most recent expression in the rule input must be as old as possible.
* Expressions matched in the same order as the rules are written, or, if not possible, in the smallest permutation of that order (i.e., vector of set expression indices in the order of the rule input should be the smallest element wise).
* Rule with the smallest index is used.
* Both LowLevel and Symbolic methods now use the new updating order.
* Adds unit tests for the updating order to `correctness.wlt`.
* Run unit tests: `./build.wlt && ./install.wlt && ./test.wlt`.
* The oldest expressions are updated first, regardless of the rule index:
```
In[] := …
```

Least-recent-first updating order

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/performance.wlt

* Implements "HyperedgeType" option of HypergraphPlot.
* Possible values are "Ordered" (sequence), "Cyclic" (last vertex connect to first), and "Unordered" (all vertices in a hyperedge form a complete graph).
* Specification is per-pattern, i.e., {"Ordered", {_, _, _} -> "Cyclic"} will make hyperedges "Ordered", except for 3-edges, which will be "Cyclic".
The idea is to have three options: "HyperedgeType", GraphLayout (both vertex- and edge-layout parts), and "HyperedgeShapeFunction" (responsible for drawing).
"HyperedgeType" will have an effect on all other options, and possible can be specified with `Hyperedge` head in the future.
`"VertexLayout"` will take for the most part the same layouts as `GraphPlot`, with possible an addition of `"BraneElectricalEmbedding"`.
`"EdgeLayout"` will …

HypergraphPlot: "HyperedgeType" option

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/performance.wlt

* `HypergraphPlot` is reimplemented from scratch.
* Different graph layouts can now be supported, initially `"SpringElectricalEmbedding"` and `"SpringElectricalPolygons"`.
* `"HypergraphPlot"` now checks that option names passed to it are correct.
* Single-vertex edges are now shown as circles around the vertex.
* `"SpringElectricalPolygons"` draws a hyperedge as a convex polygon around all its vertices and normal edges.
* Closes #30 .
* Closes #82 .
* `PlotStyle` is temporarily removed. Will be added in a future PR.
* Consequently, all hyperedges now have to be the same color.
* `"EdgeType" -> "Unordered"` is removed, will be added in a future PR.
* Performance is about 3 times worse than `GraphPlot`, worse than 2 times worse it was previously.
* `RulePlot` will be added in a separate …

HypergraphPlot: SpringElectricalPolygons

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt

* Adds the ability to constrain coordinates in HypergraphPlot.
* Run unit tests: `./build.wls && ./install.wls && ./test.wls`.
* By default, `VertexCoordinates` for all vertices are chosen automatically:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, VertexCoordinates -> {}]
```
* One of the coordinates can be constrained:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, 
VertexCoordinates -> {3 -> {0, 0}}, Axes -> True, 
```
* Or more than one:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, 
VertexCoordinates -> {1 -> {0, 0}, 2 -> {1, 0}}, Axes -> True, 
```
* Sometimes layout is not optimal due to bugs in the classic `"SpringElectricalEmbedding"` code:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, 
VertexCoordinates -> …
```

HypergraphPlot: VertexCoordinates

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/performance.wlt

* Closes #87 .
* Implements `"GraphHighlight"` option of `HypergraphPlot`, which allows highlighting vertices and edges similar to `GraphPlot`.
* Run unit tests: `./build.wls && ./install.wls && ./test.wls`.
* Highlight a vertex in a hypergraph:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, GraphHighlight -> {3}]
```
* Highlight an edge:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}, GraphHighlight -> {{1, 2, 3}}]
```
* Highlight multiple vertices and edges:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 6}}, 
GraphHighlight -> {{5, 6, 6}, {1, 2, 3}, 4}]
```
* This works with other layouts as well:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 6}}, 
GraphHighlight -> {{5, 6, 6}, {1, 2, 3}, 4}, 
GraphLayout -> "SpringElectricalEmbedding"]
```

Graph highlight

---

SetReplace/libSetReplace/Match.cpp
SetReplace/libSetReplace/Match.hpp
SetReplace/libSetReplace/Set.cpp
SetReplace/libSetReplace/Set.hpp
SetReplace/libSetReplace/SetReplace.cpp
SetReplace/libSetReplace/SetReplace.hpp
SetReplace/setSubstitutionSystem$cpp.m

* Adds an interactive API to libSetReplace. Initially four functions are implemented:
* `setCreate`: creates a `Set` instance from rules and init and returns a pointer to it as an `Integer`.
* `setReplace`: atomically performs a requested number of replacements on the set given a pointer and steps spec. Does not return anything, updates the set in-place.
* `setExpressions`: returns expressions given the set pointer.
* `setDelete`: deletes the set from memory.
* `setSubstitutionSystem$cpp` is updated to use these functions.
* This makes all kinds of things possible:
* Evaluation of `setReplace` can be aborted without losing results. Results can still be obtained with `setExpressions`.
* It is possible to pause and resume evaluation.
* Using that, one can implement progress monitoring.
* We …

libSetReplace interactive API

---

SetReplace/SetReplace.m
SetReplace/SetReplace.wlt
SetReplace/SetReplaceAll.m
SetReplace/SetReplaceAll.wlt
SetReplace/SetReplaceFixedPoint.m
SetReplace/SetReplaceFixedPoint.wlt
SetReplace/SetReplaceFixedPointList.m
SetReplace/SetReplaceFixedPointList.wlt
SetReplace/SetReplaceList.m
SetReplace/SetReplaceList.wlt
SetReplace/WolframModel.m
SetReplace/WolframModel.wlt
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m
SetReplace/setSubstitutionSystem.m

* `WolframModel` now *usually* returns an evolution object when abort is triggered.
* Sometimes an abort would be triggered before or after the evolution of the system was computed, in which case the result will not be returned.
* If you are really in a hurry, just press cmd+. twice, and it will abort immediately without returning a result.
* New option `TimeConstraint` is implemented for `WolframModel` and related functions. This is guaranteed to return a result if evolution object is supposed to be returned, and will always return `$Aborted` otherwise.
* Right now, it is not possible to determine if the evolution is complete or not if generations count is requested, because the last generation might not be complete.
* Possible solution is to include "evolution targets" to the evolution …

TimeConstraint and result on Abort

---

SetReplace/utilities.m

* Adds `fromCounts` function to utilities.
* `fromCounts` is a reverse of `Counts`:
```
In[] := fromCounts[<|1 -> 3, 2 -> 2, "x" -> 4|>]
```
```
Out[] = {1, 1, 1, 2, 2, "x", "x", "x", "x"}
```
```
In[] := fromCounts[Counts@#] == # &[{1, 2, 3, 3, 3, 4, 5, 6, 6, 7}]
```
```
Out[] = True
```

fromCounts

---

SetReplace/utilities.m

* Adds `multisetIntersection` to utilities.
* Find common elements in three multisets:
```
In[] := SetReplace`PackageScope`multisetIntersection[
{1, 1, 2, 2, 3}, {1, 2, 2, 2, 4}, {1, 2, 2}]
```
```
Out[] = {1, 2, 2}
```

multisetIntersection

---

SetReplace/RulePlot.m

* Closes #102 .
* `RulePlot` now highlights shared edges as well, not just vertices.
* Check unit tests still pass: `./build.wls && ./install.wls && ./test.wls`.
* Shared edges are now highlighted:
```
In[] := RulePlot[WolframModel[{{1, 2}} -> {{1, 2}, {2, 3}}]]
```
* That includes hyperedges:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}, {3, 4, 5}} -> {{3, 4, 5}, {5, 6, 
7}}]]
```
* Makes it easier to see that an edge orientation has changed, for example:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}} -> {{2, 3, 1}}]]
```

RulePlot: Highlight shared edges

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt

* Resolves #101 .
* It is now possible to highlight one out of several identical edges.
* Run relevant unit tests: `./test.wls HypergraphPlot`.
* The following now produces correct result:
```
In[] := HypergraphPlot[{{1}, {1}, {1, 2}, {1, 2}, {2, 3, 4}, {2, 3, 4}}, 
GraphHighlight -> {{1}, {1, 2}, {2, 3, 4}}]
```

Fix: GraphHighlight for multi-edges

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.m
SetReplace/RulePlot.wlt

* Closes #103.
* Closes #104.
* Adds `GraphHighlightStyle` option for `HypergraphPlot` and `RulePlot`. Currently, it only supports colors.
* Build and test: `./build.wls&&./install.wls&&./test.wls`
* Highlighting can now be done in style:
```
In[] := HypergraphPlot[{{1}, {1}, {1, 2}, {1, 2}, {2, 3, 4}}, 
GraphHighlight -> {{1}, {1, 2}, {2, 3, 4}}, 
GraphHighlightStyle -> Purple]
```
* `RulePlot` now uses a shade of violet by default:
```
In[] := RulePlot[WolframModel[{{3}, {1, 2, 3}} -> {{1, 2, 3}, {3, 4, 5}}]]
```
* It also supports `GraphHighlightStyle` options:
```
In[] := RulePlot[WolframModel[{{3}, {1, 2, 3}} -> {{1, 2, 3}, {3, 4, 5}}], 
GraphHighlightStyle -> Orange]
```

GraphHighlightStyle

---

SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/setSubstitutionSystem$cpp.m

* Resolves #116.
* Fixes handling of nested lists in the initial condition of `WolframModel` and related functions.
* Run unit tests, old and new: `./build.wls && ./install.wls && ./test.wls`.
* The following now works as expected:
```
In[] := WolframModel[{{{2, 2, 1}, {2, 2, 2}} -> {{1, 1, 3}, {1, 1, 1}, {2, 1, 
2}, {3, 3, 2}}}, {Table[{0, 0, 0}, 3]}, 2]
```
* Specifically, in that case, each `{0, 0, 0}` is a vertex and there is a single hyperedge consisting of three of them:
```
In[] := WolframModel[{{{1, 1, 1}} -> {{1, 1, 1, 1}}}, {Table[{0, 0, 0}, 
3]}, 2, "FinalState"]
```
```
Out[] = {{{0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}}}
```

Fix handling of nested lists in C++ interface

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.m
SetReplace/RulePlot.wlt
SetReplace/performance.wlt

* Closes #106.
* `"EdgeType"` is no longer an option in `HypergraphPlot`, but a second argument instead.
* Run unit tests: `./build.wls && ./install.wls && ./test.wls`.
* Specify the edge type as a second argument:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, "Ordered"]
```
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, "CyclicClosed"]
```
* `"CyclicOpen"` is the default:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}]
```

HypergraphPlot: Edge type argument

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.m
SetReplace/RulePlot.wlt
SetReplace/performance.wlt

* Closes #119.
* Replaces `"CyclicOpen"` and `"CyclicClosed"` edge types with a single `"Cyclic"` edge type.
* `"SpringElectricalPolygons"` with edge type `"Ordered"` is now rendered as it was rendered with edge type `"CyclicOpen"` previously.
* Otherwise, `"Cyclic"` is rendered as `"CyclicClosed"`.
* Run tests: `./build.wls&&./install.wls&&./test.wls`
* `"Ordered"` edge type is now rendered semi-cyclically by `HypergraphPlot`:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, "Ordered"]
```
* All supported layouts and edge types are:
```
In[] := Dataset@Association@
Table[layout -> 
Association@
Table[edgeType -> 
HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, edgeType, 
GraphLayout -> layout], {edgeType, {"Ordered", 
"Cyclic"}}], {layout, {"SpringElectricalEmbedding", …
```

EdgeType: "Cyclic"

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.m
SetReplace/RulePlot.wlt
SetReplace/performance.wlt

* Closes #105.
* Renames `GraphLayout` option to `"HyperedgeRendering"` in `HypergraphPlot` and `RulePlot`.
* `"SpringElectricalEmbedding"` now became `"Subgraphs"`.
* `"SpringElectricalPolygons"` became just `"Polygons"`.
* Run tests: `./build.wls && ./install.wls && ./test.wls`
* Use `"HyperedgeRendering"` to switch between *normal graph* and *polygons* layouts:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, 
"HyperedgeRendering" -> "Subgraphs"]
```
* All options for rendering are now:
```
In[] := Dataset@Association@
Table[hyperedgeRendering -> 
Association@
Table[edgeType -> 
HypergraphPlot[{{1, 2, 3}, {3, 4, 5}, {3, 6, 7}}, edgeType, 
"HyperedgeRendering" -> 
hyperedgeRendering], {edgeType, {"Ordered", 
"Cyclic"}}], {hyperedgeRendering, {"Subgraphs", "Polygons"}}]
```

HyperedgeRendering

---

SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.wlt
SetReplace/SetReplace.wlt
SetReplace/SetReplaceAll.wlt
SetReplace/SetReplaceFixedPoint.wlt
SetReplace/SetReplaceFixedPointList.wlt
SetReplace/SetReplaceList.wlt
SetReplace/ToPatternRules.wlt
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.wlt
SetReplace/correctness.wlt
SetReplace/meta.wlt
SetReplace/performance.wlt
SetReplace/testUtilities.m
build.wls
install.wls
test.wls

* Resolves #125.
* Closes #68.
* Changes `.wlt` files to the new format, which allows for parsing and auto parallelizing of tests.
* `./test.wls` now replaces all `VerificationTest` heads in `.wlt` files with an inactive tests, collects and flattens all tests, and then runs them in parallel (an option for not running in parallel is available).
* It also now prints a descriptive message in case of tests failures saying what the input was, and what outputs (or messages) were obtained and expected.
* All scripts, `./build.wls`, `./install.wls` and `./test.wls` now return non-zero exit codes in case of failures or messages, which allows integration into automated systems, such as CI.
* As a side effect of refactoring, tests will also now check (for all functions) whether the expressions stay …

Descriptive test failures

---

.fire.yml

* Replaces local Docker image with one downloadable from a private Docker Hub repository in Fire CI config.
* Now, in order to run Fire CI, only three steps are necessary:
* Install Docker.
* Install Fire CI agent.
* Log in to `maxitg` Docker account using the Fire CI agent.

Use Docker Hub image in Fire CI

---

install.wls

* Due to changes in the paclet system, install script is now failing to uninstall the paclet.
* The script now does not attempt to manually uninstall, and install passes `IgnoreVersion -> True` to `PacletInstall`.
* CI.

Fix install script for WL build 6542432

---

install.wls

That did not fix the issue. Paclet still cannot be reinstalled if the version is the same.

Revert "Fix install script for WL build 6542432"

---

.circleci/config.yml
.fire.yml
install.wls

* Instead of uninstalling the paclet, the install script now uses `"IgnoreVersion" -> True`.
* It also uses the new way to verify paclet installation on 12.1.
* Updates CIs to install the paclet twice to make sure it can be reinstalled.
* CI.

Fix installation for new paclet system in 12.1

---

SetReplace/WolframModel.wlt
SetReplace/libSetReplace/Set.cpp
SetReplace/libSetReplace/Set.hpp
SetReplace/libSetReplace/SetReplace.cpp
SetReplace/makeMessage.m
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m
SetReplace/setSubstitutionSystem.m

* Adds an option to limit the maximum vertex degree in the step specification.
* This is especially useful in `Method -> "LowLevel"`, because that implementation becomes exponentially slow in some cases when vertex degrees are large.
* Run new unit tests.
* Limit max vertex degree for a universe that tends to grow vertices with large degrees (86337):
```
In[] := WolframModel[{{1, 2}, {1, 2}, {3, 1}} -> {{1, 1}, {1, 4}, {2, 1}, {2, 
4}, {4, 3}}, {{1, 1}, {1, 1}, {1, 1}}, <|"MaxVertexDegree" -> 20|>]
```
```
In[] := HypergraphPlot[%[-1]]
```

Max vertex degree step constraint

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.m

* Adds new options to `HypergraphPlot`:
* `VertexStyle`: controls the style for vertices.
* `EdgeStyle`: controls the style of edge lines. Also affects the style for unary edges and hyperedge polygons if they are set to `Automatic`.
* `"UnaryEdgeStyle"`: controls the style of circles that represent unary edges.
* `"EdgePolygonStyle"`: controls the style of hyperedge polygons.
* `PlotStyle`: controls the overall style of the graph. Only has an effect if either `VertexStyle` or `EdgeStyle` are set to `Automatic` (which they are not by default).
* `VertexSize`: controls the size of vertices.
* `"ArrowheadLength"`: controls the length of arrowheads.
* Note, the sizes in `HypergraphPlot` are always absolute. The length scale of graph edges is around `1`, and vertices are always the same size …

HypergraphPlot styles

---

SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt

* Adds `"LayeredCausalGraph"` property to `WolframModel` and `WolframModelEvolutionObject`, which returns the same `Graph` as `CausalGraph`, but arranges the heights of events based on their generations.
* Adds `"EventGenerations"` property, which returns the list of generations for all events.
* Produce a causal graph for a particular system (this was possible before):
```
In[] := WolframModel[{{1, 2}, {1, 3}, {2, 4}} -> {{1, 3}, {1, 5}, {2, 4}, {2, 
5}, {4, 5}}, {{1, 1}, {1, 1}, {1, 1}}, 11, "CausalGraph"]
```
* Now, arrange events generation-by-generation:
```
In[] := WolframModel[{{1, 2}, {1, 3}, {2, 4}} -> {{1, 3}, {1, 5}, {2, 4}, {2, 
5}, {4, 5}}, {{1, 1}, {1, 1}, {1, 1}}, 11, "LayeredCausalGraph"]
```
* Change the height of each layer:
```
In[] := WolframModel[{{1, 2}, {1, 3}, {2, …
```

Layered causal graph

---

SetReplace/HypergraphPlot.m
SetReplace/HypergraphPlot.wlt
SetReplace/utilities.m

* Closes #153.
* Styles in `HypergraphPlot` can now be specified per element, or per element pattern.
* Specifically, there are now three ways to specify a style (`EdgeStyle` used as an example, but the same works for `"EdgePolygonStyle"` and `VertexStyle`):
* `EdgeStyle -> style` (use the same style for everything);
* `EdgeStyle -> <|pattern -> style, ...|>` (use different styles for different patterns of edges);
* `EdgeStyle -> {style1, style2, ...}` (specify styles for each edge).
* Removes `"UnaryEdgeStyle"` option, which is superseded by specifying a corresponding pattern in `EdgeStyle`, i.e., `"EdgeStyle" -> <|..., {_} -> unaryStyle|>`.
* `PlotStyle` can now be specified directly without manually setting `EdgeStyle` and `VertexStyle` to automatic, as it's default now uses patterns …

Elementwise HypergraphPlot styles

---

SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/libSetReplace/Match.cpp
SetReplace/libSetReplace/Match.hpp
SetReplace/libSetReplace/Set.cpp
SetReplace/libSetReplace/Set.hpp
SetReplace/libSetReplace/SetReplace.cpp
SetReplace/libSetReplace/SetReplace.hpp
SetReplace/performance.wlt
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m

* Adds `"MaxCompleteGenerations"` property (and entry to the evolution object), which would return the last generation for which no more matches can be made.
* Given current evaluation order, it will be either the same as `"GenerationsCount"`, or one less than that, but the code allows generalization to other evaluation orders.
* Note, previous versions of the evolution objects are no longer compatible and would produce corrupt evolution object messages. One way to get around that is to manually add ``SetReplace`PackageScope`$maxCompleteGeneration -> Missing[]`` to the evolution object.
* If backwards compatibility with previous evolution objects is required that can be arranged, but it seems at this point it is better to avoid unnecessary complicating the code.
* Evaluate a system for a …

MaxCompleteGenerations

---

SetReplace/WolframModel.m
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m

* Adds an option to remove partial generations from the evolution object and other properties.
* The option `"IncludePartialGenerations"` can be used with both `WolframModel` and `WolframModelEvolutionObject`.
* Setting this option to `False` essentially creates a new evolution object with removed partial generations before computing any other properties, which means it will automatically work for new properties without any additional code.
* If `$maxCompleteGeneration` is set to `Missing[]`, a message is generated if `"IncludePartialGenerations" -> False`, but properties with `"IncludePartialGenerations" -> True` can still be calculated.
* Create an evolution object with partial generations:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {2, 3}}, {{1, 1}}, <|
"MaxEvents" -> 200|>] …
```

IncludePartialGenerations

---

SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt

* Changes `"LayeredCausalGraph"` property to use `"LayeredDigraphEmbedding"` instead of "SpringElectricalEmbedding".
* This produces embeddings that are less entangled than previously.
* Produce a picture that better illustrates the structure of the causal graph:
```
In[] := WolframModel[{{1}, {1}} -> {{1}, {1}, {1}}, {{1}, {1}}, 13, \
"LayeredCausalGraph"]
```
* For a tree, we will no longer have entangled branches:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}, {3, 2}}, {{1, 
1}}, 4, "LayeredCausalGraph"]
```
* Label vertices:
```
In[] := WolframModel[{{1, 2}, {1, 3}, {1, 4}} -> {{2, 3}, {2, 4}, {3, 3}, {3, 
5}, {4, 5}}, {{1, 1}, {1, 1}, {1, 1}}, 6]["LayeredCausalGraph", 
```

LayeredDigraphEmbedding for LayeredCausalGraph

---

SetReplace/HypergraphPlot.wlt
SetReplace/RulePlot.wlt
SetReplace/SetReplace.wlt
SetReplace/SetReplaceAll.wlt
SetReplace/SetReplaceFixedPoint.wlt
SetReplace/SetReplaceFixedPointList.wlt
SetReplace/SetReplaceList.wlt
SetReplace/ToPatternRules.wlt
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.wlt
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m
SetReplace/testUtilities.m

* Resolves #163.
* Assignes `Temporary` attribute to all relevant symbols created with `Unique[]` and so on, so that they don't cause a memory leak.
* The symbols affected are new atom names (which are created even with `"NodeNamingFunction" -> All`, but are now automatically removed after renaming is done), and symbols used in patterns in symbolic WL code.
* There was also a `Module` symbol where `Attributes` were manually assigned without `Temporary`.
* Run new unit tests checking for leaked symbols.
* The memory use ***before*** this PR (LowLevel code):
```
In[] := ListPlot[Table[
WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}, 9, 
"GenerationsCount", Method -> "LowLevel"]; MemoryInUse[], 10]]
```
* Symbolic code ***before***:
```
In[] := ListPlot[Table[
WolframModel[{{1, …
```

Fix leaked symbols

---

SetReplace/WolframModel.m
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt

* Closes #134.
* Adds `"IncludeBoundaryEvents"` option for `WolframModel` and `WolframModelEvolutionObject`.
* Currently affects `"EventsCount"`, `"EventGenerations"`, `"CausalGraph"` and `"LayeredCausalGraph"`.
* The initial event is `0`, the final event is `Infinity`.
* The initial event's generation is `0`, the final event's generation is `1 + "GenerationsCount"`.
* For large initial conditions causal graph might appear disconnected if there is no information passed between parts of the initial condition:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}}, {{1, 2}, {2, 3}, {3, 
4}, {4, 5}}, 3]["CausalGraph", VertexLabels -> Automatic]
```
* Use `"IncludeBoundaryEvents"` option to include the initial event (i.e., event that creates the initial condition):
```
In[] := …
```

IncludeBoundaryEvents

---

SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m

* Closes #170.
* Event numbers are now sequential after removing incomplete generations.
* Note that event numbers here are `Range[13]` instead of being large random numbers:
```
In[] := SeedRandom[2];
WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}, <|
"MaxEvents" -> 500|>, "EventOrderingFunction" -> "Random", 
"IncludePartialGenerations" -> False]["CausalGraph", 
```

Sequential incomplete events

---

SetReplace/SetReplace.xcodeproj/project.pbxproj
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt
SetReplace/libSetReplace/Set.cpp
SetReplace/libSetReplace/Set.hpp
SetReplace/libSetReplace/SetReplace.cpp
SetReplace/libSetReplace/SetReplace.hpp
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m

* Closes #83.
* Implements tracking of rule indices used for each replacement.
* Adds `"AllEventsRuleIndices"` and `"AllEventsList"` properties for the evolution object:
* `"AllEventsRuleIndices"` yields a list of indices of the rules used for each update. `0` is used for the initial condition, and `Infinity` is used for the final state event.
* `"AllEventsList"` yields a list of events which have the format `{ruleIndex, input -> output}`, where `input` and `output` are lists of indices of expressions in `"AllExpressions"`.
* Consider a model which makes use of multiple rules:
```
In[] := obj = WolframModel[{{{1, 2}, {2, 3}} -> {{1, 3}, {1, 4}, {2, 4}, {4, 
1}}, {{1, 2}, {3, 2}} -> {{1, 2}}}, {{1, 1}, {1, 1}}, 5]
```
* Check that both rules are used:
```
In[] := …
```

AllEventsRuleIndices & AllEventsList

---

SetReplace/RulePlot.m
SetReplace/RulePlot.wlt
SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt
SetReplace/performance.wlt

* Renames `HypergraphPlot` -> `WolframModelPlot`.
* Use `WolframModelPlot` now to plot hypergraphs:
```
In[] := WolframModelPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 1}}]
```
* Arguments are options are the same as were previously in `HypergraphPlot`:
```
In[] := WolframModelPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 1}}, 
VertexLabels -> Automatic, GraphHighlight -> {{1, 2, 3}, 5}]
```

WolframModelPlot

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Brings back `HypergraphPlot` for compatibility.
* Its `OwnValue` is simply assigned to `HypergraphPlot`, together with `Options` and `SyntaxInformation`.
* Do you see any obvious problems with assigning the `OwnValue` in this way?
* `HypergraphPlot` can be used again:
```
In[] := HypergraphPlot[{{1, 2, 3}, {3, 4, 5}}]
```
* The usage message says it is deprecated:
```
In[] := ?HypergraphPlot
```

Restore HypergraphPlot

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Disallows vertices that a lists in `WolframModelPlot`.
* This is a preparation for a later PR that is going to plot a sequence of hypergraphs.
* If we want to automatically distinguish between a single hypergraph and a list of hypergraphs, we have to disallow edges that are lists.
* List-vertices no longer work:
```
In[] := WolframModelPlot[{{{1, 1}, 2, 3}, {3, 4, 5}}]
```
```
During evaluation of In[] := WolframModelPlot::invalidEdges: First argument of WolframModelPlot must be list of lists, where elements represent vertices.
Out[] = WolframModelPlot[{{{1, 1}, 2, 3}, {3, 4, 5}}]
```
* Use a custom head for composite vertices:
```
In[] := WolframModelPlot[{{v[1, 1], 2, 3}, {3, 4, 5}}, 
```

Not allow List-vertices in WolframModelPlot

---

SetReplace/HypergraphAutomorphismGroup.m
SetReplace/HypergraphAutomorphismGroup.wlt

* Implements `HypergraphAutomorphismGroup` function, which is similar to `GraphAutomorphismGroup`.
* Works by turning the hypergraph into a normal graph, and then taking subgroup of that graph's automorphism group.
* While `GraphAutomorphismGroup` is generally faster than the matching algorithm (particularly evident for torus graphs), adding vertices when converting hyper- to normal graph adds a significant performance hit. There might be a better approach to this which would avoid introducing new vertices, obtain an overly-symmetric group for the normal graph, and then take a subgroup of that based on which transformations are not allowed in the hypergraph.
* Obtain automorphism group for a hyper-cycle:
```
In[] := HypergraphAutomorphismGroup[{{1, 2, 3}, {3, 4, 5}, {5, 6, 1}}]
```
``` …
```

HypergraphAutomorphismGroup

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Image size now scales automatically with the plot range for small hypergraphs (when plot range in either direction is smaller than 1).
* `ImageSizeRaw` is used so that images still become smaller if placed in lists etc.
* Nothing except for image size (i.e., graph layout etc) is affected.
* Plot an evolution of a set substitution system and observe that the first plot has a smaller image size than the others:
```
In[] := WolframModelPlot /@ 
WolframModel[{{{1, 2}} -> {{1, 3}, {1, 3}, {2, 3}}}, {{1, 1}}, 4, 
"StatesList"]
```

Automatic image size for small graphs

---

SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt
SetReplace/correctness.wlt
SetReplace/makeMessage.m
SetReplace/setSubstitutionSystem$wl.m

* Closes #85.
* Implemented new properties for `WolframModelEvolutionObject`:
* `"FinalStatePlot"`: `WolframModelPlot`s the last state,
* `"StatesPlotsList"`: yields a list of `WolframModelPlot`s,
* `"PartialGenerationsCount"`: total - complete generations,
* `"GenerationComplete"`: yields true/false depending whether the last (or specified) generation is complete,
* `"GenerationEventsCountList"`: event counts in between generations,
* `"GenerationEventsList"`: events grouped by generation,
* `"VertexCountList"`: counts of vertices at each generation,
* `"EdgeCountList"`: counts of edges at each generation,
* `"EventsStatesList"`: riffled states and events.
* Changed behavior of `"GenerationsCount"`, which now returns a list `{"CompleteGenerationsCount", "PartialGenerationsCount"}`.
* …

New property names

---

SetReplace/WolframModelPlot.m

* Removes filled convex polygon from 2-edges in "Ordered" hypergraph plots for "Polygons" hyperedge rendering.
* Does not affect "Cyclic" hypergraphs, nor "Subgraphs" hyperedge rendering.
* Does not affect the embedding of vertices.
* Two-vertex-edges are no longer filled (including 2-self-loops):
```
In[] := WolframModelPlot[{{5}, {1, 2, 3}, {3, 4}, {3, 4}, {4, 5, 6}, {6, 
1}, {2, 2}, {3, 3, 3}}]
```

Remove polygons from 2-edges

---

SetReplace/RulePlot.m
SetReplace/WolframModel.wlt
SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelPlot.m

* Changes plot styles for `WolframModelPlot`, causal graph properties, and partially `RulePlot`.
* Reduces arrow sizes in `WolframModelPlot`.
* Edge styles are different in `WolframModelPlot` and causal graphs, even though they both correspond to the same edges (shared edges define causal relations between events in causal graphs). This is done according to the design document, but it's not clear why the colors are chosen that way.
* `FrameStyle` and highlight color are still missing in `RulePlot` (they are not done in the design document).
* `WolframModelPlot` now looks different:
```
In[] := WolframModelPlot /@ 
WolframModel[{{x, y}, {y, z}} -> {{w, y}, {y, z}, {z, w}, {x, 
w}}, {{0, 0}, {0, 0}}, 10, "StatesList"]
```
```
In[] := WolframModelPlot[
WolframModel[{{x, y}, {y, z}} -> {{w, …
```

New plot styles

---

SetReplace/WolframModel.m
SetReplace/WolframModel.wlt
SetReplace/performance.wlt

* Renames `"NodeNamingFunction"` to `"VertexNamingFunction"`.
* It now always renames vertices, not atoms, even for pattern rules.
* Use `"VertexNamingFunction"` in the similar way as `"NodeNamingFunction"` was used before:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}}, {{a, a}}, 2, 
"AllExpressions", "VertexNamingFunction" -> #] & /@ {Automatic, 
All} // Column
```
* Vertices (i.e., level-2 expressions) are replaced instead of atoms:
```
In[] := WolframModel[<|"PatternRules" -> a_ :> a|>, {{{{{{{x}}}}}}}, 1, 
"FinalState", "VertexNamingFunction" -> #] & /@ {None, All}
```
```
Out[] = {{{{{{{{x}}}}}}}, {{1}}}
```

VertexNamingFunction

---

SetReplace/WolframModel.wlt

* Workaround for Wolfram bug #387470.
* Removes small time `TimeConstrained` test to avoid bad memory access yielding wrong test results.
* This commit should be reverted once the bug is fixed.

Remove small time constraint test

---

SetReplace/libSetReplace/Match.cpp
SetReplace/libSetReplace/Match.hpp
SetReplace/libSetReplace/Set.cpp
SetReplace/libSetReplace/Set.hpp
SetReplace/libSetReplace/SetReplace.cpp
SetReplace/setSubstitutionSystem$cpp.m

* Refactors C++ code to allow specification of multiple event ordering functions.
* Reorganizes data structure containing matches into a search tree (`std::map`) of buckets / hash tables (`std::unordered_map`). The search tree is arranged according to the (possibly partial) event ordering function, the hash tables contain the matches that are equivalent according to that function.
* This allows partially random evaluation orders, in which the first bucket is selected for the next event, but a specific match is chosen from that bucket at random.
* `SortedExpressionIDs` (oldest edge first), `ReverseSortedExpressionIDs` (least recent edge first), `ExpressionIDs` (greedy comparison of edge ages one at a time according to the rule ordering), `RuleID` (sort by rule index) are implemented so …

Custom evaluation order in C++

---

SetReplace/GeneralizedGridGraph.m
SetReplace/GeneralizedGridGraph.wlt

* Implements `GeneralizedGridGraph`, which is similar to `GridGraph`, but can make the graph `"Circular"` or / and `"Directed"` in each dimension.
* Make an ordinary grid graph:
```
In[] := GeneralizedGridGraph[{10, 10}]
```
* Make it circular in one of the dimensions, and directed in another:
```
In[] := GeneralizedGridGraph[{10 -> "Circular", 10 -> "Directed"}]
```
* Make the same dimension both circular and directed:
```
In[] := GeneralizedGridGraph[{10 -> {"Circular", "Directed"}, 5}]
```
* Make a directed hypercube graph:
```
In[] := Graph[GeneralizedGridGraph[Thread[{2, 2, 2, 2} -> "Directed"]], 
GraphLayout -> "SpringElectricalEmbedding"]
```

GeneralizedGridGraph

---

SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt

* Adds special colors for initial and final events in causal graphs.
* It is now obvious which event is the initial event (since it's now blue):
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}}, {{1, 1}}, 4, "CausalGraph",
"IncludeBoundaryEvents" -> "Initial"]
```
* This also works with `"LayeredCausalGraph"`:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}}, {{1, 
1}}, 4, "LayeredCausalGraph", "IncludeBoundaryEvents" -> "Initial"]
```
* Final events are white:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {3, 2}}, {{1, 1}}, 3, "CausalGraph",
"IncludeBoundaryEvents" -> All]
```

Causal boundary colors

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Adds `"MaxImageSize"` option to `WolframModelPlot`, which allows adjusting `ImageSize` while maintaining the scaling which makes small graphs smaller.
* It can only take numeric values, and if specified it replaces the default max value of `{{360}, {420}}`, and can be smaller if the plot range is smaller than `1/0.7`.
* Before:
```
In[] := WolframModel[{{x, y}, {y, z}} -> {{w, y}, {y, z}, {z, w}, {x, 
w}}, {{0, 0}, {0, 0}}, 10]["StatesPlotsList", ImageSize -> 100]
```
* Now (note vertices have the same size on the first few images due to proportional scaling):
```
In[] := WolframModel[{{x, y}, {y, z}} -> {{w, y}, {y, z}, {z, w}, {x, 
w}}, {{0, 0}, {0, 0}}, 10]["StatesPlotsList", 
"MaxImageSize" -> 100]
```

MaxImageSize for WolframModelPlot

---

SetReplace/GeneralizedGridGraph.m
SetReplace/GeneralizedGridGraph.wlt

* Adds `Graph` options to `GeneralizedGridGraph`.
* Allows specifying different styles for edges in different directions.
* Use `"SpringEmbedding"` for the graph:
```
In[] := GeneralizedGridGraph[{5, 5}, GraphLayout -> "SpringEmbedding"]
```
* Color all edges `Red`:
```
In[] := GeneralizedGridGraph[{5, 5}, EdgeStyle -> Red]
```
* Color edges in different directions `Red` and `Blue`:
```
In[] := GeneralizedGridGraph[{5, 5}, EdgeStyle -> {Red, Blue}]
```
* Make vertical lines dotted:
```
In[] := GeneralizedGridGraph[{5, 7 -> "Directed"}, 
EdgeStyle -> {Directive[Red, Dotted], Blue}]
```

Generalized grid graph edge styles

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Changes `GraphHighlight` to quietly skip highlighting a vertex or an edge instead of throwing an error message if that vertex or edge does not exist in the hypergraph.
* This is particularly useful when highlighting an element in a sequence of hypergraphs, which we can now do without manual filtering.
* Attempting to highlight a vertex or an edge that does not exist will no longer produce an error message:
```
In[] := WolframModelPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 7}, {7, 8, 1}}, 
GraphHighlight -> {5, 7, 9, {1, 2, 3}, {2, 3, 4}}]
```
* This allows one to highlight a particular vertex throughout the entire evolution:
```
In[] := WolframModel[{{1, 2}, {1, 3}, {1, 4}} -> {{5, 6}, {6, 5}, {5, 7}, {7, 
5}, {6, 7}, {7, 6}, {5, 2}, {6, 3}, {7, 4}, {2, 7}, {4, 5}}, {{1,
1}, {1, 1}, {1, 1}}, …
```

Quiet nonexistent GraphHighlight

---

SetReplace/WolframModelPlot.m

* Default `PlotStyle` in `WolframModelPlot` is now `Automatic` instead of exposing internal variables.
* Functionality is not changed, the `Automatic` `PlotStyle` still picks up the same variable which was previously explicitly assigned to `PlotStyle` option:
```
In[] := WolframModelPlot[{{1, 2, 3}, {3, 4, 5}, {5, 6, 7}, {7, 8, 9}, {9, 10, 
1}}]
```
* However, the explicit option value is now `Automatic`:
```
In[] := Options[WolframModelPlot, EdgeStyle]
```
```
Out[] = {EdgeStyle -> Automatic}
```

Fix default plot style in WolframModelPlot

---

scripts/buildInit.wl

* Fixes the build script to work in WL build 6697939.
* This build removes `PacletInformation` from `` System` `` context, so it is now replaced with `PacletFind`.
* Run `./build.wls` twice, it would previously fail saying `GitLink` is already installed, but will now succeed:
```
>> ./build.wls && ./build.wls      
Build done.
Build done.
```

Fix GitLink install in WL build 6697939

---

SetReplace/utilities.m
SetReplace/utilities.wlt

* Implements `multisetComplement` utility function.
* Does the same as `Complement`, but preserves counts of multiple elements.
* That's useful, in particular, for hypergraph diffing.
* The following keeps the correct count of 1's in the list:
```
In[] := SetReplace`PackageScope`multisetComplement[{1, 1, 1, 2, 3}, {1, 2, 4}]
Out[] = {1, 1, 3}
```
* Compare:
```
In[] := Complement[{1, 1, 1, 2, 3}, {1, 2, 4}]
Out[] = {3}
```

multisetComplement

---

SetReplace/WolframModel.m
SetReplace/WolframModel.wlt
SetReplace/correctness.wlt
SetReplace/setSubstitutionSystem$cpp.m
SetReplace/setSubstitutionSystem$wl.m
SetReplace/setSubstitutionSystem.m

* Closes #7 (oldest open issue!).
* Allows using different C++ evaluation orders in `"EventOrderingFunction"` options.
* Orders currently supported are: `"OldestEdge"`, `"LeastOldEdge"`, `"LeastRecentEdge"`, `"NewestEdge"`, `"RuleOrdering"`, `"ReverseRuleOrdering"`, `"RuleIndex"`, `"ReverseRuleIndex"`, `"Random"`.
* Lists of these are also supported, in which case the next one in the list is used in case of collisions.
* If the list of specified functions is not sufficient to determine priority, the random among smallest is chosen (hence, i.e., `{}` can be used instead of `"Random"`).
* Evolve a `WolframModel` with all individual event ordering functions:
```
In[] := WolframModel[{{1, 2}, {1, 3}, {1, 4}} -> {{5, 6}, {6, 7}, {7, 5}, {5, 
7}, {7, 6}, {6, 5}, {5, 2}, {6, 3}, {7, 4}, {2, 7}, …
```

Custom evaluation order

---

SetReplace/WolframModel.m
SetReplace/WolframModel.wlt

* Closes #133.
* Allows use of `Automatic` instead of the initial state.
* All anonymous rules are supported, but pattern rules are not.
* Use "compactified" left-hand side of the rule as an initial condition:
```
In[] := WolframModel[{{1, 2}, {2, 3}} -> {{1, 2}, {2, 4}, {4, 1}, {4, 3}}, 
Automatic][0]
```
```
Out[] = {{1, 1}, {1, 1}}
```
```
In[] := WolframModel[{{1, 2}, {2, 3}} -> {{1, 2}, {2, 4}, {4, 1}, {4, 
3}}, Automatic, 10, "FinalStatePlot"]
```
* In the case of multiple rules, the minimal combination of both is used such that each rule can still be applied:
```
In[] := WolframModel[{{{1}, {1, 2}} -> {{1, 2}, {2}}, {{1, 2}, {2, 3}} -> {{1,
3}, {3, 2}, {2, 4}}}, Automatic, 5, "StatesPlotsList"]
```

Automatic init

---

SetReplace/RulePlot.m
SetReplace/RulePlot.wlt

* Changes colors for the frame around `RulePlot` parts and the arrow.
* Changes the shape of the arrow.
* Adds support for `Frame -> Automatic`, which only draws a frame for multiple rules.
* Add proportional scaling of `ImageSizeRaw` with plot range.
* We need an official design color for the arrow, the frame, and the shared vertex/edge highlight as well.
* `Frame -> Automatic` is not the default for `RulePlot`, and we cannot change it without overwriting the whole system. It needs to be changed upstream.
* New look for `RulePlot`:
```
In[] := RulePlot[WolframModel[{{{1, 1, 2}} -> {{1, 2, 3}, {2, 2, 1}, {2, 3, 
2}}, {{1, 2, 1}, {3, 4, 2}} -> {{4, 3, 2}}}]]
```
* New look with `Frame -> Automatic`:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}, {4, 5, 6}, {1, 4}} -> {{2, 7, 
8}, {9, 3, …
```

New frame and arrow for RulePlot

---

SetReplace/WolframModelEvolutionObject.m
SetReplace/WolframModelEvolutionObject.wlt

* Implements `"EventsStatesPlotsList"` property of `WolframModel` and `WolframModelEvolutionObject`.
* That produces plots similar to `WolframModelPlot /@ WolframModel[..., "AllEventsStatesList"]`, however, it also highlights edges that were just created and edges that are about to be destroyed.
* Setting `"IncludeBoundaryEvents" -> "Initial"` or `"IncludeBoundaryEvents" -> "Final"` highlights all initial edges as just created, and all final edges as about to be destroyed respectively.
* @sskini2, could you ask Jeremy if the style for the edge that is both just created and about to be destroyed is good?
* The tests only check the code does not fail with error messages. They don't test if the pictures produced are correct, as we don't have the technology for that yet.
* Show evolution of a …

EventsStatesPlotsList

---

SetReplace/RulePlot.m
SetReplace/RulePlot.wlt

* Adds `"RulePartsAspectRatio"` option to `RulePlot`, which controls the aspect ratio of rule-side boxes.
* The default value is `Automatic`, which chooses the aspect ratio based on the rule shape.
* If multiple rules are present, chooses the aspect ratio closest to 1, or exactly 1 if the aspect ratios go opposite ways for different rules.
* Default `RulePlot` now uses an automatic aspect ratio:
```
In[] := RulePlot[WolframModel[{{1, 3}, {2, 3}} -> {{1, 2}, {2, 3}, {3, 4}, {3,
5}}], Frame -> Automatic]
```
* But custom aspect ratio can be specified as well:
```
In[] := RulePlot[WolframModel[{{1, 3}, {2, 3}} -> {{1, 2}, {2, 3}, {3, 4}, {3,
5}}], Frame -> Automatic, "RulePartsAspectRatio" -> 1.2]
```
* Aspect ratio is limited from 0.2 to 5 to avoid extremely skinny rules in cases like this: …

Non-square RulePlot

---

SetReplace/GeneralizedGridGraph.m
SetReplace/GeneralizedGridGraph.wlt

* Adds an option to name vertices in `GeneralizedGridGraph` with their coordinates.
* Use `"VertexNamingFunction" -> "Coordinates"` to name vertices according to their coordinates:
```
In[] := GeneralizedGridGraph[{3, 4}, "VertexNamingFunction" -> "Coordinates", 
```
* That works with other types of grids as well:
```
In[] := GeneralizedGridGraph[{3 -> "Circular", 4 -> "Directed"}, 
"VertexNamingFunction" -> "Coordinates", VertexLabels -> Automatic]
```
* And in arbitrary dimension:
```
In[] := GeneralizedGridGraph[{3, 4, 2}, 
"VertexNamingFunction" -> "Coordinates", VertexLabels -> Automatic]
```
* Default value is `Automatic`, in which case an `IndexGraph` is produced:
```
In[] := GeneralizedGridGraph[{3, 4}, VertexLabels -> Automatic]
```

VertexNamingFunction for GeneralizedGridGraph

---

SetReplace/WolframModelEvolutionObject.m
SetReplace/setSubstitutionSystem.m

* Changes `WolframModelEvolutionObject` to use strings instead of internal symbols for the association keys and termination reason values.
* This ***considerably*** simplifies WFR deployment, as one does no longer need to worry about managing contexts of internal symbols.
* Does not affect functionality.

Strings for evolution object keys/values

---

SetReplace/WolframModelPlot.m
SetReplace/WolframModelPlot.wlt

* Allows supplying a list of hypergraphs to `WolframModelPlot`, in which case it returns the list of plots.
* All options are passed to each of the plots.
* For now, it's identical to mapping `WolframModelPlot` over the list of hypergraphs.
* Highlighting of new / deleted edges etc. will come in a separate PR.
* Plot a list of hypergraphs:
```
In[] := WolframModelPlot[{{{1, 2, 3}, {3, 4, 5}}, {{3, 4, 5}, {5, 6, 7}}, {{5,
6, 7}, {7, 8, 9}, {9, 10, 1}}}]
```
* Highlight the same vertex on all of them:
```
In[] := WolframModelPlot[{{{1, 2, 3}, {3, 4, 5}}, {{3, 4, 5}, {5, 6, 7}}, {{5,
6, 7}, {7, 8, 9}, {9, 10, 1}}}, GraphHighlight -> {3}]
```

Listable WolframModelPlot

---

SetReplace/utilities.m
SetReplace/utilities.wlt

* Implements `multisetUnion` utility function.
* Does the same as `Union`, but preserves counts of multiple elements.
* Will be used for computing unified embeddings of multiple hypergraphs.
* The following keeps correct counts of 1's and 2's in the list:
```
In[] := SetReplace`PackageScope`multisetUnion[{1, 2, 2, 3}, {1, 1, 2, 4}]
Out[] = {1, 1, 2, 2, 3, 4}
```
* Compare to `Union` that "loses" elements:
```
In[] := Union[{1, 2, 2, 3}, {1, 1, 2, 4}]
Out[] = {1, 2, 3, 4}
```

multisetUnion

---

SetReplace/WolframModel.m
SetReplace/WolframModelEvolutionObject.m

* Adds autocompletion for `WolframModel` properties.
* Legacy option names are not listed, only the new ones.
* Does not work for `WolframModelEvolutionObject` at this time.
* If someone knows how to add autocompletion for the evolution object (i.e., for `SubValues`), please let me know.
* Fuzzy matching algorithm does not seem to work here, but it also does not work for entities, so that looks like a frontend bug.
* Start typing the option name and enjoy:
* Old option names are not autocompleted though, i.e., `"AllExpressions"` is hidden:

WolframModel properties autocompletion

---

build.wls
scripts/buildInit.wl

* Allows the user to choose the context for the paclet at build time.
* `CONTEXT` environment variable can be explicitly set to the desired context.
* Alternatively, `CONTEXT="Version"` makes the version-specific context chosen automatically.
* This is needed to insulate Wolfram Function Repository functions from each other and from separately-installed SetReplace.
* Build normally to get a default ``SetReplace` `` context:
```
>> ./build.wls&&./install.wls
Build done.
Installed. Restart running kernels to complete installation.
In[] := Quit
In[] := << SetReplace`
In[] := SetReplace`WolframModel[1 -> 2, {1}, "FinalState"]
Out[] = {2}
```
* Specify the context explicitly:
```
>> CONTEXT="SR" ./build.wls&&./install.wls
Building with context SR`
Build done.
Installed. Restart running kernels …
```

Custom context

---

SetReplace/WolframPhysicsProjectStyleData.m
SetReplace/WolframPhysicsProjectStyleData.wlt
SetReplace/style.m

* Implements `WolframPhysicsProjectStyleData`.
* If called with 0 arguments, it returns the entire style association for the `"Light"` plot theme, which is the only theme available at the moment.
* If called with 1 argument, which is a plot theme, returns the association for that plot theme.
* Can also take a style group and an (optional) style element arguments after the theme specification (if any).
* Get all styles for the physics project:
```
In[] := WolframPhysicsProjectStyleData[]
```
* Get values for all causal graph styles:
```
In[] := WolframPhysicsProjectStyleData["CausalGraph"]
```
* Get the value of the default vertex size:
```
In[] := WolframPhysicsProjectStyleData["SpatialGraph", "VertexSize"]
Out[] = 0.06
```
* This is equivalent to extracting the same value from the …

WolframPhysicsProjectStyleData

---

SetReplace/ToPatternRules.m
SetReplace/ToPatternRules.wlt

* Closes #219.
* Output of `ToPatternRules` does no longer depend on the names of anonymous variables.
* The following two examples previously produced different results.
```
In[] := ToPatternRules[{{1, 2}, {1, 3}} -> {{1, 2}, {1, 4}, {2, 4}, {3, 4}}]
Out[] = {{v1_, v2_}, {v1_, v3_}} :> 
Module[{v4}, {{v1, v2}, {v1, v4}, {v2, v4}, {v3, v4}}]
```
```
In[] := ToPatternRules[{{x, y}, {x, z}} -> {{x, y}, {x, w}, {y, w}, {z, w}}]
Out[] = {{v1_, v2_}, {v1_, v3_}} :> 
Module[{v4}, {{v1, v2}, {v1, v4}, {v2, v4}, {v3, v4}}]
```

Fix ToPatternRules pattern naming

---

SetReplace/RulePlot.wlt

* One of the `RulePlot` tests got broken after the kernel changed the default `Frame -> Automatic` in `RulePlot`.
* It was checking whether the style for the frame was applied, but the frame was never created due to the different option value.
* Added explicit `Frame -> True`, so that it now passes.

Frame style test fix

---

SetReplace/utilities.m
SetReplace/utilities.wlt

* Implements a multiset version of `FilterRules`.
* Filter exactly as many rules as are specified in the second argument.
* Useful for splitting unified hypergraph embedding back into component hypergraphs.
* The following picks up exactly the number of rules from the list as specified by the second argument, but not more than that:
```
In[] := SetReplace`PackageScope`multisetFilterRules[{1 -> a, 2 -> b, 2 -> c, 
2 -> d, 3 -> e, 3 -> f}, {2, 2, 3, 3, 3}]
Out[] = {2 -> b, 2 -> c, 3 -> e, 3 -> f}
```

multisetFilterRules

---

Kernel/style.m

* Adds styles for `"SpatialGraph3D"`, `"StatesGraph3D"`, `"RulialGraph"`, `"GenericLinePlot"`, and `"GenericGraph"`.
* Styles are contributed by *Jeremy Davis*.
* Please check whether the names for plots and styles make sense.
* In particular, do `"GenericLinePlot"` only apply to line plots, or should I drop the "Line" from the name?
* I did not include `"VertexSize"` for `"SpatialGraph3D"`, because the value 2 supplied by Jeremy only makes sense for that particular size of the graph.
* For `"RulialGraph"`, the vertex styles are different depending on whether vertices are rendered as "icons" (labels), or circles. Thus, the icon versions of the names are `"VertexIcon*"`. If you have a better word instead of "icon", let me know.
* I did not include any styles for `"EvolutionCausalGraph3D"` …

Generic, 3D, and rulial graph styles

---

Kernel/WolframModelPlot.m
Kernel/style.m
Tests/WolframModelPlot.wlt

* Closes #217.
* Make the arrowheads adaptively change from `0.1` to `0.185` depending on the size of the graph.
* The style spec is contributed by *Jeremy Davis*.
* The arrowhead function is now in `style.m`. This is the first precedent where a function is used for a style.
* Comparison of old arrowheads (on the left), and the new adaptive ones (on the right):
```
In[] := Grid@Transpose[
WolframModel[{{1, 2, 3}, {4, 5, 6}, {1, 4}} -> {{2, 7, 8}, {3, 9, 
10}, {5, 11, 12}, {6, 13, 14}, {8, 12}, {11, 10}, {13, 
7}, {14, 9}}, {{1, 1, 1}, {1, 1, 1}, {1, 1}, {1, 1}, {1, 1}},
3]["EventsStatesPlotsList", "ArrowheadLength" -> #] & /@ {0.1, 
Automatic}]
```
* The new spec makes it possible to see arrows on graphs 1.85 larger than before:
```
In[] := WolframModel[{{1, 2}, {2, 3}} -> {{4, 2}, {4, …
```

Adaptive arrowheads

---

Kernel/HypergraphUnifications.m
Tests/HypergraphUnifications.wlt

* Resolves #220.
* Fixes `HypergraphUnifications` for non-overlapping hypergraphs.
* Non-overlapping hypergraphs can only occur if there are no edges with the same arity, so this case is not very common.
* The reason was inconsistent levels in the output of `Reap`.
* Failing cases from #220 now work and return empty lists:
```
In[] := HypergraphUnifications[{}, {}]
Out[] = {}
```
```
In[] := HypergraphUnifications[{{1}}, {}]
Out[] = {}
```
```
In[] := HypergraphUnifications[{{1, 2}}, {{1, 2, 3}}]
Out[] = {}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/264)

Fix empty hypergraph unifications

---

Kernel/buildData.m
Tests/buildData.wlt
build.wls
scripts/buildInit.wl
scripts/packPaclet.wls

* Closes #231.
* Adds two constants that are defined at build time:
* `$SetReplaceGitSHA` contains the SHA of the repo from which the paclet was built. `*` added at the end, if the repo is dirty.
* `$SetReplaceBuildTime` contains the `DateObject` of the build time.
* The `$SetReplaceBuildTime` is in UTC because I don't think the timezone is particularly important.
* This is useful to put into research notebooks so that we can be certain we can reproduce them.
* Compare `$SetReplaceGitSHA` with the last commit on GitHub:
```
In[] := $SetReplaceGitSHA
Out[] = "95a60da2c3fe95fba3774337f97f4855282a1553"
```
* Check that build time makes sense:
```
In[] := $SetReplaceBuildTime
```
* Checked that this works for internal builds as well.
--- …

Git SHA and Build Time

---

Kernel/WolframModelPlot.m
Kernel/arrow.m
Kernel/style.m
Tests/WolframModelPlot.wlt

* Closes #240.
* Does three optimizations:
* Speeds up drawing of arrowheads by (1) skipping them altogether is `"ArrowheadLength" -> 0`, and optimizing the computation of shape embeddings otherwise.
* Fixes a weed by which `drawEmbedding` would still make a call to `GraphPlot` to obtain `VertexLabels` even if `None` were requested.
* The largest optimization: streamlines `drawEmbedding` function by only including a style once in the result if no elementwise styles were specified.
* Note that the largest optimization is not on the kernel side, but on the frontend side (the filesize of the images should decrease as well, although I did not check that).
* This is because the graphics objects produced are now much smaller, only contain element styles once, and don't have nested `Rotate`, …

WolframModelPlot drawing optimizations

---

libSetReplace/IDTypes.hpp
libSetReplace/Match.cpp
libSetReplace/Match.hpp
libSetReplace/Set.cpp
libSetReplace/Set.hpp
libSetReplace/SetReplace.cpp

* Closes #109.
* Closes #221.
* Makes C++ code check function arguments internally, so that it does not crash if incorrect arguments are passed.
* In line with that, fixes the atom index overflow issue, so that it is now possible to produce evolutions with more than `2^31` vertices/edges.
* Does not affect functionality, evolution still works as expected:
```
In[] := WolframModel[{{x, y}, {x, z}} -> {{x, y}, {x, w}, {y, w}, {z, 
w}}, {{1, 2}, {1, 3}}, 15, "FinalStatePlot"]
```

Secure C++ code

---

Kernel/WolframModel.m
Kernel/WolframModelEvolutionObject.m
Tests/WolframModel.wlt

* Allows `Automatic` for step count.
* The default automation corresponds to `<|"MaxEvents" -> 5000, "MaxEdges" -> 200|>`.
* In addition, `TimeConstraint` is set to `5`, and partial generations are dropped.
* Additionally these constraints can be multiplied by a factor (and are rounded if the result is non-integer). This is specified as `{Automatic, factor}`.
* `"TerminationReason"` in that case is set to `Automatic`.
* Note that because of `TimeConstraint`, the behavior is non-deterministic.
* Automate everything!
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 
2}}, Automatic, Automatic, "FinalStatePlot"]
```
* Make a 10 times larger version:
```
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 
2}}, Automatic, {Automatic, 10}, "FinalStatePlot"]
```
---
This change …

Automatic Steps

---

Kernel/style.m

* Changes colors for generic line plots.
* Styles are contributed by *Jeremy Davis*.
* Check the new colors:
```
In[] := WolframPhysicsProjectStyleData["GenericLinePlot", "PlotStyles"]
```

Change generical line plot styles

---

Kernel/WolframModelPlot.m
Tests/WolframModelPlot.wlt

* Resolves #279.
* Adds tests for style inheritance.
* Tests don't currently work in that they don't test the `Graphics` object produced is valid. Correct tests are in #281.
* This needs to be merged first, however, in order to fix CI failure in #281.
* This is ***P0 critical***, as `WolframModelPlot` currently fails in many cases.
* The previously failing example now works correctly:
```
In[] := WolframModelPlot[{{1, 2}}, GraphHighlight -> {2}, PlotStyle -> Black]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/282)

Fix style inheritance

---

scripts/buildInit.wl

* Fixes #222.
* Build script no longer requires an Internet connection.
* This is achieved by removing unnecessary `GitFetch`, and using `master` instead of `origin/master` to determine the version number.
* Disconnect from the Internet.
* Run `./build.wls`, and check the paclet file created has the correct version:
```
>> SetReplace git:(internalBuild) ./build.wls && ls *.paclet           
Build done.
SetReplace-0.2.95.paclet
```
* Also checked internal builds still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/271)

Offline Build

---

build.wls
scripts/buildInit.wl
scripts/packPaclet.wls
scripts/re_build_SetReplace.xml

* Allows changing the paclet context in internal builds by setting `env.CONTEXT` variable.
* This significantly simplifies the workflow of making WFR paclet files for all architectures.
* If the paclet is created with a custom context (i.e., the WFR version), `-C` is appended to the paclet name, so that it's not accidentally confused with a normal paclet.
* Build the paclet with the version context and check the filename contains `-C` suffix:
```
>> CONTEXT="Version" ./build.wls && ls *.paclet
Building with context SetReplace$0$2$95`
Build done.
SetReplace-0.2.95-C.paclet
```
* Also checked that internal builds work (with and without a custom context).
--- …

Allow context change in internal builds

---

Kernel/testUtilities.m
Tests/RulePlot.wlt
Tests/WolframModelEvolutionObject.wlt
Tests/WolframModelPlot.wlt

* Implements `graphicsQ` and `checkGraphics` functions.
* Both of these functions check if a given `Graphics` object would generate front-end errors (pink background ones) if displayed in the Front End.
* `graphicsQ` simply returns `True` if the given `Graphics` object is valid, and `False` otherwise.
* And `checkGraphics` prints all front-end errors as ordinary messages, and returns the `Graphics` back. This is useful to insert inside other tests without changing their structure.
* Both of these functions momentarily flash a new front-end window, but that is ok because these are meant to be used mostly on a CI server.
* This is ***critical*** because it catches #279, it cannot be merged until both #280 and the fix for #279 are merged.
* Most of this PR are just insertions of `graphicsQ` …

graphicsQ and checkGraphics

---

Kernel/RulePlot.m
Tests/RulePlot.wlt

* Partly implements #152.
* Adds `PlotStyle`, `VertexStyle`, `EdgeStyle`, `"EdgePolygonStyle"`, `VertexSize` and `"ArrowheadLength"` options to `RulePlot` of `WolframModel`.
* Tests are not failing because test functions from #281 are not merged yet, even though they are used here. Without those functions, failing graphics are missed.
* Style options are currently broken due to #279. #282 will need to be merged first.
* Use a different `PlotStyle`:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}} -> {{3, 4, 5}}], 
PlotStyle -> RGBColor[0.01, 0.40, 0.98]]
```
* `VertexSize` can now be adjusted:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}} -> {{3, 4, 5}}], 
VertexSize -> #] & /@ {0, 0.1, 0.2}
```
* So can be `"ArrowheadLength"`:
```
In[] := RulePlot[WolframModel[{{1, 2, 3}} -> {{3, 4, 5}}], …
```

RulePlot hypergraph styles

---

Kernel/WolframModelPlot.m

* Improves placement of vertex labels.
* `VertexLabels` are now placed with an edge-aware `GraphPlot`, which does edge avoidance in some cases.
* `VertexLabels` are now aware of `VertexSize` which prevents them from being too close and overlapping vertices in some cases.
* (Obviously) changes all graphics where vertex labels were included.
* Makes an issue of vertex labels escaping outside `RulePlot` frame more likely. Unfortunately, there is no good solution for this within a current setup because vertex labels change size depending on image size.
* Does not affect performance for `VertexLabels -> None`. Slightly affects performance otherwise (but vertex labels are not particularly useful for large graphs).
* Before (048311f4139cd7146e3879c710b02cc0c90a72e5):
```
In[] := …
```

Improved vertex labels

---

Kernel/WolframModelPlot.m
Tests/RulePlot.wlt
Tests/WolframModelPlot.wlt

* Allow any style to be used in `GraphHighlightStyle` (previously only single colors were allowed).
* `GraphHighlightStyle` works on the level of `PlotStyle`, which means the style is the same for all graph elements, and there is no way to control inherited things like edge polygon opacity, etc.
* Make highlight `Red`, `Thick`, and `Dashed`:
```
In[] := WolframModelPlot[{{1, 2, 3}, {3, 4, 5}}, 
GraphHighlight -> {{1, 2, 3}, 4}, 
GraphHighlightStyle -> Directive[Red, Thick, Dashed]]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/285)

Any highlight style

---

Kernel/WolframModelPlot.m
Tests/WolframModelEvolutionObject.wlt
Tests/WolframModelPlot.wlt

* Fixes #286.
* Fixes style parsing for empty hypergraphs.
* This also fixes `"EventsStatesPlotsList"` for empty states.
* All it took was removing a dot from `{$hypergraphPattern...}` (the rest is code style and tests).
* This fixes the vertex icons weed in MultiwaySystem.
* This now works correctly:
```
In[] := WolframModelPlot[{}, VertexStyle -> {}]
```
* And so are the `"EventsStatesPlotsList"`s:
```
In[] := WolframModel[{{1, 2}} -> {}, {{1, 
2}}, \[Infinity], "EventsStatesPlotsList"]
```
```
In[] := WolframModel[{} -> {{1, 2}}, {}, <|
"MaxEvents" -> 1|>, "EventsStatesPlotsList"]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/287)

Fix style parsing for empty hypergraphs

---

Kernel/HypergraphUnificationsPlot.m
Tests/HypergraphUnificationsPlot.wlt

* Implements `HypergraphUnificationsPlot`.
* Visualizes the result of `HypergraphUnifications` by differently coloring unification components.
* `VertexLabels -> Automatic` labels vertices according to the corresponding vertices of the unification arguments.
* Show unifications for two binary hypergraphs:
```
In[] := HypergraphUnificationsPlot[{{x, y}, {x, z}}, {{a, b}, {b, c}}]
```
* Include vertex labels:
```
In[] := HypergraphUnificationsPlot[{{x, y}, {x, z}}, {{a, b}, {b, c}}, 
```
* A more complicated example:
```
In[] := HypergraphUnificationsPlot[{{1, 2}, {2, 3, 4}, {4, 5}}, {{x, y, 
z}, {z, a, b}, {z, w}}, VertexLabels -> Automatic]
```
--- …

HypergraphUnificationsPlot

---

Kernel/utilities.m
Tests/utilities.wlt

* Implements `connectedHypergraphQ`.
* This will be used to test if a rule is connected.
* Yields `False` for a disconnected hypergraph:
```
In[] := SetReplace`PackageScope`connectedHypergraphQ[
EchoFunction[
WolframModelPlot]@{{10, 17, 14}, {15, 8, 9}, {18, 15, 14}, {3, 12, 
18}, {0, 16, 5}, {8, 13, 14}}]
```
* Yields `True` for a connected one:
```
In[] := SetReplace`PackageScope`connectedHypergraphQ[
EchoFunction[
WolframModelPlot]@{{13, 1, 14}, {13, 2, 16}, {16, 14, 18}, {6, 10, 
15}, {1, 13, 15}, {13, 13, 15}}]
```
* Can handle a simplified unary edge syntax as well:
```
In[] := SetReplace`PackageScope`connectedHypergraphQ[{1, {1, 2}}]
Out[] = True
```
--- …

connectedHypergraphQ

---

libSetReplace/SetReplace.cpp

* Restores compilation on 32-bit Windows, which was previously broken.
* `mint` on 32-bit Windows is a 32-bit `int`, whereas event and vertex IDs are 64 bit.
* This caused a compilation error for the code that passed the result from C++ code back to WL.
* I'm now doing a `static_cast` of these 64-bit numbers to 32-bit `mint`s, which would generally do the right thing except for the cases where the evolution produces more than 2 billion vertices/edges/events, which is not possible on a 32-bit machine anyway due to 4 GB memory limit.
* Would be great to test this on a 32-bit Windows machine, but I don't have any. We'll eventually need to use CI for such things, but for now, at least we know the 64-bit version is not broken, and the paclet can be compiled for 32-bit Windows.
---
This change …

Fix compilation on 32-bit Windows.

---

Kernel/WolframModel.m
Tests/WolframModel.wlt

* Fixes #294.
* Fixes scaling of time constraint if using `Automatic` steps (so that, i.e., `{Automatic, 0.2}` is 5 times faster than `Automatic`).
* `WolframModel` now returns even non-evolution-object if a time constraint is triggered in the course of `Automatic` steps evaluation, even if time constraint is specified manually.
* It's ok to return incomplete results in the case of `Automatic` steps, as `Automatic` steps behavior is undefined anyway.
* Time constraint scaling now works correctly:
```
In[] := AbsoluteTiming[
WolframModel[{{1, 1}, {1, 1}, {1, 1}} -> {{1, 1}, {1, 1}, {1, 
1}, {1, 1}}, Automatic, {Automatic, #}]] & /@ {0.04, 0.2, 
1} // Grid
```
* And results are now correctly returned for properties after time constraint is triggered:
```
In[] := WolframModel[{{1, 1}, {1, …
```

Fix automatic time constraint

---

Kernel/style.m

* Fix a typo in `style.m`, where `"CreatedEdgeStyle"` was set to `$destroyedEdgeStyle` instead of `$createdEdgeStyle`.
* This only affects `WolframPhysicsProjectStyleData`.
* It does not affect `"EventsStatesPlotsList"`.
* Created edge style is now correct:
```
In[] := WolframPhysicsProjectStyleData["SpatialGraph", "CreatedEdgeStyle"]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/296)

Fix created edge style

---

Kernel/HypergraphUnifications.m
Kernel/HypergraphUnificationsPlot.m
Kernel/ToPatternRules.m
Kernel/WolframModelRuleValue.m
Kernel/WolframPhysicsProjectStyleData.m

* Clarifies usage messages for `HypergraphUnifications`, `HypergraphUnificationsPlot`, `ToPatternRules`, `WolframModelRuleValue`, and `WolframPhysicsProjectStyleData`.
* Only changes usage strings. It does not affect functionality.
* Check the new usage messages:
```
In[] := ?HypergraphUnifications
```
```
In[] := ?HypergraphUnificationsPlot
```
```
In[] := ?ToPatternRules
```
```
In[] := ?WolframModelRuleValue
```
```
In[] := ?WolframPhysicsProjectStyleData
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/302)

Clean up usage messages

---

PacletInfo.m
scripts/buildInit.wl
scripts/version.wl

* Bumps version number to 0.3 :tada:, and sets the checkpoint to 58de7583018f3688e4f94cdd3bac1500df95f9df.
* Decreases the minor version counting by one so that the version immediately after merging this PR is 0.3.0, not 0.3.1.
* Once this is merged, a new release should be created with the cross-platform paclet attached.
* Build the paclet and check the version is correct:
```
>> ./build.wls && ls *.paclet      
Build done.
SetReplace-0.3.0.paclet
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/304)

SetReplace 0.3

---

libSetReplace/IDTypes.hpp

To be self-consistent and include all the headers IDTypes.hpp needs.
I am guessing IDTypes.hpp is included
in a compilation unit where cstdint is included.
cpp-reference: https://en.cppreference.com/w/cpp/types/integer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/308)

Add header cstdint to IDTypes providing int64_t

---

libSetReplace/Expression.cpp
libSetReplace/Match.cpp
libSetReplace/SetReplace.cpp

* Optimized some cases of hash table lookups such that they occur less
* Reduced number of `std::vector::push_back` calls in favor of either `std::vector::reserve`+`std::vector::emplace_back` or `std::vector::resize`+`std::vector::operator[]` to reduce number of memory allocations
* A few other small changes, such as spelling/code style consistency
* No functionality is changed
The following is a basic example of reducing hash table lookups (worst case O(n) with size of container)
Before:
```c++
if (index_.count(atom)) {
return index_.at(atom);
} else {
return {};
}
```
After:
```c++
const auto resultIterator = index_.find(atom);
return resultIterator != index_.end() ? resultIterator->second : std::unordered_set<ExpressionID>();
```
--- …

Reduced number of hash table lookups and memory allocations

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/weed_report.md
README.md

* Adds language specifiers to code snippets in markdown files to enable syntax highlighting on GitHub.
* This affects the weed report template, contributing guidelines, and README.
* This PR is very simple, it just adds `wl` to a bunch of lines (also `html` and `bash` in one place each).
* If you are reading this after 4/18/2020 12 AM EDT, please merge this pull request after review (if not requesting any changes), don't wait for @maxitg.
* Code snippets before:
```
In[] := WolframModel[{{1, 2, 3}, {2, 4, 5}} ->
{{5, 6, 1}, {6, 4, 2}, {4, 5, 3}},
{{1, 2, 3}, {2, 4, 5}, {4, 6, 7}}, 10]
```
* Now:
```wl
In[] := WolframModel[{{1, 2, 3}, {2, 4, 5}} ->
{{5, 6, 1}, {6, 4, 2}, {4, 5, 3}},
{{1, 2, 3}, {2, 4, 5}, {4, 6, 7}}, 10]
```
--- …

Add syntax highlighting to markdown files

---

.github/CONTRIBUTING.md

* Separated Code Style section in contributing guidelines to two sections: Wolfram Language and C++
* Specified exceptions to guidelines
* Described how to use cpplint properly and what to do if there are any linting errors
* Closes #315
* This is the first step in addressing the C++ refactoring effort
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/318)

C++ Style contributing guidelines update

---

.circleci/config.yml
.circleci/test.sh
test.wls

* Resolves #327.
* Makes `./test.wls` write its expected exit status to a file, which is then read by CI. This prevents CI from succeeding if Wolfram Kernel crashes with exit status 0.
* It appears that Wolfram Kernel sometimes crashes with exit status 0, as happened in [this build](https://app.circleci.com/pipelines/github/maxitg/SetReplace/583/workflows/e90468f6-cfc3-4a84-9f67-f5dbee24830b/jobs/622/steps).
* This PR makes the CI run a bash script instead, which makes `./test.wls` write its status to a text file at the end of execution, and then checks that text file to determine the CI status.
* This way, if `./test.wls` finishes running, its exit status would be the same as CIs, but if it crashes, the file would not exist, and CI will fail anyway.
* Cherry-pick these commits on top of …

Verify test completion in CI

---

libSetReplace/Expression.cpp
libSetReplace/Expression.hpp
libSetReplace/Match.cpp
libSetReplace/Match.hpp
libSetReplace/Set.cpp
libSetReplace/Set.hpp
libSetReplace/SetReplace.cpp

* Increased usage of STL functions for efficiency.
* Reduced instances of pass-by-value to reduce amount of copying, particularly vectors. 
* Reduced amount of hash lookups (sets/maps). Although complexity is constant, lookups are quite expensive.
* Increased usage of foreach loops
* Some other misc. optimizations
Overall performance is increased by up to 37% in one test I ran of WolframModel.
* No functionality changes.
* As a bonus, these commits include auto code formatting. This partially addresses #319. You may see a lot of erasures on blank lines. Many IDEs including mine erase white space to reduce file size.
Testing setup functions:
```wl
Attributes[meanAroundTiming] = {HoldAll};
meanAroundTiming[expr_, measurementsCount_ : 5] := 
MeanAround@Table[First@AbsoluteTiming[expr], …
```

Cpp optimizations

---

performanceTest.wls

* After completing tests on both input SHAs, performs `git checkout` on original git SHA.
Originally, if running from `SHA_1`:
```bash
./performanceTest.wls SHA_2 SHA_3
```
would leave you on `SHA_3`.
With this change, running the same command would leave you on SHA_1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/356)

performanceTest.wls checkout original SHA

---

.github/CONTRIBUTING.md
CMakeLists.txt
cmake/FindMathematica.cmake
cmake/SetReplaceConfig.cmake.in
libSetReplace/test/CMakeLists.txt
libSetReplace/test/SetTest.cpp

Providing:
- target (library) `SetReplace`
- config files for third-parties CMake projects
to use SetReplace with no need of FindSetReplace.cmake
- Usable from build and install trees.
- Option to use with or without Mathematica.
- Infrastructure to perform cpp tests with gtest.
CMake options:
- `SET_REPLACE_BUILD_TESTING`:
Download gtest at build time (with FetchContent) and enable
basic cpp testing.
OFF by default.
- `SET_REPLACE_WITH_MATHEMATICA`:
Compiles `SetReplace.cpp` which provides the interface for Wolfram Language.
For this `FindMathematica.cmake` is needed.
`FindMathematica.cmake` is taken from:
https://github.com/sakra/FindMathematica/blob/master/CMake/Mathematica/FindMathematica.cmake
that seems used and up-to-date.
Please note that FindX.cmake is deprecated in CMake, and …

Add CMake support

---

libSetReplace/SetReplace.cpp
scripts/buildInit.wl

* Resolves #359.
* Resolves compilations errors on Windows-32.
* `mint` on 32-bit Windows is 32-bit, however, `Atom` is `int64_t`. Because of that, conversion from `AtomList` to `std::vector<mint>` was failing on line 147.
* This is now replaced with an `std::vector<mint>` range constructor.
* We don't expect anyone with a 32-bit Windows to generate over 2 billion vertices in a single simulation, so this change should not cause any issues.
* Also, internal builds did not fetch master if building non-master, which is now fixed (without breaking normal offline builds).
* Internal builds are now succeeding: [Windows_Build_132.log](https://github.com/maxitg/SetReplace/files/4645336/Windows_Build_132.log)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Fix Windows compilation errors.

---

.circleci/config.yml
.clang-format
.github/CONTRIBUTING.md
SetReplace.xcodeproj/project.pbxproj
libSetReplace/Expression.cpp
libSetReplace/Expression.hpp
libSetReplace/IDTypes.hpp
libSetReplace/Match.cpp
libSetReplace/Match.hpp
libSetReplace/Rule.hpp
libSetReplace/Set.cpp
libSetReplace/Set.hpp
libSetReplace/SetReplace.cpp
libSetReplace/SetReplace.hpp
libSetReplace/test/Set_test.cpp
lint.sh

* This closes the C++ Style Refactor project.
* Resolves #316.
* Resolves #317.
* Resolves #319.
* Closes #357.
* Reformats all C++ code according to [Google C++ Style Guide].
* Adds `.clang-format` file specifying the exceptions to the Google style guide.
* Adds lint.sh script which prints a diff generated by `clang-format` (if any) and the errors generated by `cpplint`, and allows one to apply formatting in place with `./lint.sh -i`.
* Adds Lint step to CI before Build.
* Updates .gitbub/CONTRIBUTING.md with instructions on how to use lint.sh.
* Adds the missing test file to the Xcode project.
* Linting in CI is not parallelized and is using the same Docker image because it will eventually include linting of the Wolfram Language code as well as described in #247.
* Bin packing is now …

Lint script

---

test.wls

* Resolves https://github.com/maxitg/SetReplace/issues/70
* Fixes test results not being saved in report notebooks.
[testReport.nb.zip](https://github.com/maxitg/SetReplace/files/4674806/testReport.nb.zip)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/363)

Fully store test report in a notebook

---

libSetReplace/test/CMakeLists.txt

The file is named `Set_test.cpp`, changed from `SetTest.cpp`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/366)

CMake: Fix name of test file

---

README.md
scripts/buildInit.wl

* Fixes failing compilation on Mac introduced in #364.
* The minimum macOS target is now 10.12 (the previous ones don't support `std::shared_mutex`).
* I'm aware you might not have macOS, but I don't know where to find a reviewer who does.
* Before:
```
➜  SetReplace git:(master) ./build.wls  
CreateLibrary::cmperr: Compile error:
/Users/maxitg/Development/SetReplace/libSetReplace/Match.cpp:165:16: error:
'shared_mutex' is unavailable: introduced in macOS 10.12
buildLibSetReplace::fail: Compilation failed.
Paclet will be created without low level implementation.
Build failed.
```
* After:
```
➜  SetReplace git:(fixMacSharedMutex) ./build.wls 
Build done.
```
--- …

Fix macOS compilation for std::shared_mutex

---

.clang-format
libSetReplace/test/Set_test.cpp

* Changes the order of headers in `Set_test.cpp`, so that `cpplint` does not fail an Mac.
* Adds the corresponding rules to `.clang-format` (taken from #357).
* Apparently, the difference is due to version 1.5.0 that was released 4 days ago. Updating the CI now.
* Before:
```
➜  SetReplace git:(master) ./lint.sh
libSetReplace/test/Set_test.cpp:5:  Found C++ system header after other system header.
Should be: Set_test.h, c system, c++ system, other.  [build/include_order] [4]
Done processing libSetReplace/test/Set_test.cpp
Total errors found: 1
```
* After:
```
➜  SetReplace git:(fixTestHeaderOrder) ./lint.sh
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/373)

Fix test header formatting

---

SetReplace.xcodeproj/project.pbxproj

* Resolves #369.
* Removes "Development Team" from the Xcode project, so that it can now be immediately compiled by anyone.
* Changes C++ dialect to gnu++17 from gnu++14 (it does not compile otherwise).
* Adds Mathematica.app to the headers search path.
* Not sure if anyone is using Xcode except for me, I'll leave this open for now. If there are no reviews until Friday night, I'll just merge it myself.
* If you see this and are using Xcode, please either review or leave a comment if you don't have access.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/374)

Fix Xcode project

---

CMakeLists.txt
Kernel/setSubstitutionSystem$cpp.m
Kernel/setSubstitutionSystem$wl.m
SetReplace.xcodeproj/project.pbxproj
libSetReplace/Event.cpp
libSetReplace/Event.hpp
libSetReplace/Expression.hpp
libSetReplace/IDTypes.hpp
libSetReplace/Match.cpp
libSetReplace/Match.hpp
libSetReplace/Set.cpp
libSetReplace/Set.hpp
libSetReplace/SetReplace.cpp
libSetReplace/SetReplace.hpp
libSetReplace/test/Set_test.cpp

* Partially implements #335.
* Adds `EventSelectionFunction` to `libSetReplace`. Two are supported at the moment:
* `GlobalSpacelike`: default singleway evolution;
* `None`: match-all multiway system.
* `libSetReplace` fully supports both now, however, WL code always calls `GlobalSpacelike` (for now).
* Refactors the causal relationships tracking in `libSetReplace`. Specifically, the evolution history is now events-based instead of expressions-based, and is tracked by the `CausalGraph` class outside of `Set`:
* In my opinion, this is a better approach. Besides addressing the performance problem which would otherwise arise from tracking multiple destroyer events, it lets us fix #372, and makes it easier to deal with things like partially empty events.
* Currently, there is nothing …

EventSelectionFunction in libSetReplace

---

Kernel/WolframModel.m
Kernel/WolframModelEvolutionObject.m
Kernel/makeMessage.m
Kernel/setSubstitutionSystem$cpp.m
Kernel/setSubstitutionSystem$wl.m
README.md
Tests/WolframModelEvolutionObject.wlt

* Resolves #372.
* Adds the `"Version"` key to the evolution object, so that the versions can be tracked and migrated.
* Changes the evolution object from expression-based to event-based data format.
* Implements migration from version 1 to version 2. A message is printed to alert the user about #372.
* The new keys are `"Version"`, `"Rules"`, `"MaxCompleteGeneration"`, `"TerminationReason"`, `"AtomLists"`, `"EventRuleIDs"`, `"EventInputs"`, `"EventOutputs"`, and `"EventGenerations"`.
* Because we now explicitly track inputs for each event, `"EventList"` property can now return them in the correct order.
* Symbolic evolution is also changed to use event-based data structures internally.
* The weed #372 mentioned previously is now fixed. The event inputs are returned in the correct order: …

Event-based evolution object

---

Kernel/WolframModelEvolutionObject.m
README.md
Tests/WolframModelEvolutionObject.wlt

* Adds `"GenerationEdgeIndices"` property which returns the list of edge indices at a particular generation (i.e., edge indices for the output of `"Generation"`).
* Return edge indices:
```wl
In[] := WolframModel[{{1, 2, 3}, {4, 5, 6}, {1, 4}} -> {{2, 7, 8}, {3, 9, 
10}, {5, 11, 12}, {6, 13, 14}, {8, 12}, {11, 10}, {13, 7}, {14, 
9}}, {{1, 1, 1}, {1, 1, 1}, {1, 1}, {1, 1}, {1, 1}}, 
6]["GenerationEdgeIndices", 2]
Out[] = {10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 
27, 28, 29}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/385)

GenerationEdgeIndices

---

libSetReplace/Expression.cpp
libSetReplace/Expression.hpp
libSetReplace/Match.cpp
libSetReplace/Match.hpp
libSetReplace/Set.cpp

* Added typedef for getAtomsVector for easier usage.
* Changed signature of getAtomsVector to take in a const reference.
* Changed signature of getAtomsVector to return a const reference, to reduce forgo copying if used in a const reference context.
* Only a performance refactor.
```bash
./performanceTest.wls 10
Single-input rule                       0.33 ▒ 0.25 %
Medium rule                             -0.6 ▒ 0.5 %
Sequential rule                         -1.55 ▒ 0.28 %
Large rule                              -0.4 ▒ 1.1 %
Exponential-match-count rule            -0.63 ▒ 0.25 %
CA emulator                             9. ▒ 4. %
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setr …

Reduce Copying in getAtomsVector

---

Kernel/WolframModelEvolutionObject.m
Tests/WolframModel.wlt

* Fixes #386.
* Expression indices in event inputs/outputs are now sequential as expected.
* The rules for replacing all with new indices were already there, apparently I just forgot to use them.
* Tests introduced in #171 did not detect this because event indices were non-sequential then, not expressions.
* Trimming incomplete generations now works correctly:
```wl
In[] := SeedRandom[7]; 
WolframModel[{{1, 2}, {3, 2}} -> {{4, 1}, {4, 2}, {1, 2}, {4, 
3}}, {{1, 1}, {1, 1}}, <|"MaxEvents" -> 14|>, 
"EventOrderingFunction" -> "Random", 
"IncludePartialGenerations" -> False]["ExpressionsEventsGraph", 
```
* Evolution objects now index expressions correctly:
```wl
In[] := SeedRandom[7];
WolframModel[{{1, 2}, {3, 2}} -> {{4, 1}, {4, 2}, {1, 2}, {4, 
3}}, {{1, 1}, {1, …
```

Fix incorrect expression indexing if trimming incomplete generations

---

libSetReplace/Set.cpp
libSetReplace/test/Set_test.cpp

* Fix Set::replaceOnce() such that it does not always fail.
Before fix:
```c++
TEST(Set, ReplaceOnce) {
Matcher::OrderingSpec orderingSpec = {
{Matcher::OrderingFunction::SortedExpressionIDs, Matcher::OrderingDirection::Normal},
{Matcher::OrderingFunction::ReverseSortedExpressionIDs, Matcher::OrderingDirection::Normal},
{Matcher::OrderingFunction::ExpressionIDs, Matcher::OrderingDirection::Normal},
{Matcher::OrderingFunction::RuleIndex, Matcher::OrderingDirection::Normal}};
Set set({{{{-1}}, {{-1, -1}}}}, {{1}}, {}, orderingSpec, 0);
EXPECT_EQ(set.replaceOnce(doNotAbort), 1);
}
```
yields
```
Expected equality of these values:
set.replaceOnce(doNotAbort)
Which is: 0
1
```
After fix:
```
[ RUN      ] Set.ReplaceOnce
[       OK ] Set.ReplaceOnce (0 ms)
```
--- …

Fix replaceOnce

---

Kernel/utilities.m
Tests/utilities.wlt

* Adds two utility functions: `mapHold` and `heldPart`.
* `mapHold` maps `Hold` over specified levels. Note, it's not as simple as `Map[Hold, ...]` because `Map` will not hold its second argument.
* `heldPart` holds and returns a specified part of an expression. This is also non-trivial because `Part` does not hold it's contents.
* This is useful for Wolfram Language (`Method -> "Symbolic"`) implementation of `WolframModel`, as it deconstructs/reconstructs pattern rules, parts of which need to be held.
* This is an internal utility, it's not meant to be used outside of *SetReplace*, so it does not check its arguments.
* Extract held parts of an expression:
```wl
In[] := SetReplace`PackageScope`heldPart[{1 + 1, 2 - 2, 0*1}, 1]
Out[] = Hold[1 + 1]
```
* Map `Hold` over a list:
```wl
In[] := …
```

mapHold and heldPart

---

Kernel/WolframModelEvolutionObject.m

* Fixes #403.
* Reevaluating the input cell does no longer reset the image size in the following output cell.
* `WolframModelPlot` properties were not affected by this.
* In Wolfram Language, `Graphics` and related functions (like `Graph`) would typically keep the output image the same size even if the code that generated it is changed and reevaluated.
* However, they only do that if `ImageSize` is not specified as an option. Note that even though `ImageSize -> Automatic` is a default, explicitly specifying `ImageSize -> Automatic` as an option will prevent this size-preserving behavior from happening.
* So, this change prevents the default `ImageSize -> Automatic` from being passed to `Graph`. Note if `ImageSize` is manually specified as an argument for the property (even if `ImageSize …

Resetting Graph image size workaround

---

Research/LocalMultiwaySystem/LocalMultiwaySystem.md

* Adds documentation links from all the property/function references (multiple links if they are referenced multiple times).
* Simplifies some calls to `MultiwaySystem` where `Graph` was unnecessarily used for modifying options.
* There will be more changes soon from Wolfram internal DQA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/425)

Documentation links from Local Multiway System note

---

.clang-format
libSetReplace/test/Set_test.cpp

* Apparently, there were some changes to `cpplint`, and it now expects gtest headers to go above C++ std headers.
* This PR reorders the headers and removes custom ordering from .clang-format.
* `./lint.sh` no longer produces any error messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/435)

Make .clang-format consistent with cpplint

---

README.md

* Fixes README to always use italics when mentioning *SetReplace*.
* It was previously used inconsistently between *SetReplace* and **SetReplace**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/441)

Use italics consistently for SetReplace

---

libSetReplace/test/Set_test.cpp

* Fixes existing C++ tests.
* `Set_test.cpp` became stale after a change to the *libSetReplace* API. It is now updated and works.
* Tests now build as expected:
```bash
mkdir build && cd build 
cmake .. -DSET_REPLACE_BUILD_TESTING=ON
cmake --build .
```
```
Scanning dependencies of target SetReplace
[  5%] Building CXX object CMakeFiles/SetReplace.dir/libSetReplace/Event.cpp.o
[ 11%] Building CXX object CMakeFiles/SetReplace.dir/libSetReplace/Expression.cpp.o
[ 17%] Building CXX object CMakeFiles/SetReplace.dir/libSetReplace/Match.cpp.o
[ 23%] Building CXX object CMakeFiles/SetReplace.dir/libSetReplace/Set.cpp.o
[ 29%] Linking CXX static library libSetReplace.a
[ 29%] Built target SetReplace
Scanning dependencies of target gtest
[ 35%] Building CXX object …
```

Fix C++ tests

---

Kernel/ToPatternRules.m
Tests/ToPatternRules.wlt
libSetReplace/Match.cpp

* Closes #149.
* Replacing `ReplaceAll` with `Replace` at the correct levels.
```wl
In[]:= ToPatternRules[{{1, 2}, {2, 3}, {3, 1}} -> {{{1, 2}, {2, 3}, {3, 1}, {1, 4}, {2, 4}, {3, 4}}}]
Out[]= {{v1_, v2_}, {v2_, v3_}, {v3_, v1_}} :> Module[{v4, v5, v6, v7, v8, v9}, {{v4, v6, v8, v5, v7, v9}}]
In[]:= ToPatternRules[{{1, 2}, {2, 3}, {3, 1}} -> {{{1, 4}, {1, 4}}}]
Out[]= {{v1_, v2_}, {v2_, v3_}, {v3_, v1_}} :> Module[{v4}, {{v4, v4}}]
In[]:= ToPatternRules[{} -> {{{1, 2}}, {1, 2}}]
Out[]= {} :> Module[{v1, v2, v3}, {{v3}, {v1, v2}}]
In[]:= ToPatternRules[{{1, 2}} -> {{{1, 4}}, {1, 4}, {1, 2}, {{1, 2}}}]
Out[]= {{v1_, v2_}} :> Module[{v3, v4, v5}, {{v5}, {v1, v3}, {v1, v2}, {v4}}]
In[]:= ToPatternRules[{{{1, 2}}, {1, 2}} -> {}]
Out[]= {{v3_}, {v1_, v2_}} :> {}
```
--- …

Correct replacement of rule symbols inside ToPatternRules

---

.circleci/test.sh
test.wls

* Close #223.
* Adding `-e` option in `./test.wls`: this runs all tests except the ones specified after `-e`.
* Modifying `.circleci/test.sh` to run `./test.wls -e performance` instead of `./test.wls`.
```
./test.wls -e performance evolutionConsistency WolframModelPlot matching WolframModel WolframModelEvolutionObject
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/451)

Removing "performance" tests from CI

---

Kernel/WolframModel.m

* Closes #463.
* Taking outside the condition `recognizedOptionQ` in `WolframModel` so that `expr` can be passed correctly to it.
```wl
In[] := WolframModel[1 -> 3, {1, 2}, Metho -> "WolframLanguage"]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/465)

Fix broken message for invalid options in WolframModel

---

Kernel/WolframModelEvolutionObject.m
Tests/WolframModelEvolutionObject.wlt

* Closes #160.
* Adding error message when implicit `"Generations"` is called with additional arguments.
* I'm unsure whether I should put the message in `makeMessage.m`.
```wl
In[] := obj = WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}];
obj[1, 1]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/470)

Fix Evolution object with multiple numeric arguments leaking internal symbols

---

Kernel/RulePlot.m
Kernel/WolframModelEvolutionObject.m
Tests/RulePlot.wlt
performanceTest.wls

* Closes #230.
* Added support for passing `WolframModelEvolutionObject` to `RulePlot`.
* Adding `PackageScope[evolutionDataQ]` to test the wellness of the object.
* Is `evolutionDataQ` the best way to test that an evolution object is correct?
```wl
In[] := obj = WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}];
RulePlot[obj]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/471)

Added support for passing WolframModelEvolutionObject to RulePlot

---

libSetReplace/Set.cpp

* Avoid performing unnecessary checks for step limits (final expressions/atoms count, and atom degrees) if the corresponding step limits are disabled.
* Find while browsing results from #428.
* Run performance tests:
```
> ./performanceTest.wls master avoidUnnecessaryTerminationChecks 20
Testing master
Build done.
Uninstalling previous SetReplace at /Users/maxitg/Library/Mathematica/Paclets/Repository/SetReplace-0.3.64
Installed to /Users/maxitg/Library/Mathematica/Paclets/Repository/SetReplace-0.3.66
Restart running kernels to complete installation.
CloudConnect::clver: Connecting to a cloud running an earlier version of the Wolfram Engine: 12.1
Testing avoidUnnecessaryTerminationChecks
Build done.
Uninstalling previous SetReplace at …
```

Avoid unnecessary step limit checks

---

Kernel/HypergraphUnifications.m
Kernel/IndexHypergraph.m
Kernel/Subhypergraph.m
Kernel/utilities.m
README.md
Tests/IndexHypergraph.wlt
Tests/Subhypergraph.wlt

* Closes #80.
* Expose `IndexHypergraph` utility function.
* Moving `hypergraphQ` and some `General` messages to `Kernel/utilities.m`
* Better examples of the use of this function are appreciated.
```wl
In[] := IndexHypergraph[{{x, y, z}, {y, z, {y}}}]
Out[] = {{1, 2, 3}, {2, 3, 4}}
```
```wl
In[] := IndexHypergraph[{{x, y, z}, {y, z, y}}, -5]
Out[] = {{-5, -4, -3}, {-4, -3, -4}}
```
```wl
In[] := IndexHypergraph[]
During evaluation of In[] := IndexHypergraph::argt: IndexHypergraph called with 0 arguments; 1 or 2 arguments are expected.
Out[] = IndexHypergraph[]
```
```wl
In[] := IndexHypergraph[{x, y, {z}}, 2]
During evaluation of In[] := IndexHypergraph::invalidHypergraph: The argument at position 1 in IndexHypergraph[{x,y,{z}},2] is not a valid hypergraph.
Out[] = IndexHypergraph[{x, …
```

Add IndexHypergraph function

---

Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md

* Fixes the broken links to the "Confluence and Causal Invariance" research note.
* The links were broken after the documentation was split into multiple files #466.
* Check the links now work correctly: [rendered version](https://github.com/maxitg/SetReplace/blob/fixConfluenceAndCausalInvarianceLinks/Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/496)

Fix links to new documentation in Confluence and Causal Invariance note

---

Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md

* Adds a link to the original glossary (in addition to the archived version).
* The archive link is quite slow and does not anchor correctly in Safari, so it's useful to have the original link as well. If the content is changed, people can still verify easily using the second archived link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/501)

Confluence and Causal Invariance: Link original glossary

---

Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md

* Removes unnecessary quotes around `MultiwaySystem`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/502)

Confluence and Causal Invariance: Remove MultiwaySystem quotes

---

README.md

* `IsomorphicHypergraphQ` was missing from the index of functions in the main README file. This PR adds it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/513)

Add IsomorphicHypergraphQ to the main README file

---

.gitignore
build.wls
scripts/buildInit.wl

* `Build` directory is no longer deleted after the build is done.
* *libSetReplace* compiled library is now cached so that if the build script is called without any changes to the C++ code, it does not rebuild it making it significantly faster.
* The hash is stored in `.builtLibSetReplaceHash`. Note that it has to be outside of the `Build` directory so that it does not get copied to the paclet itself.
* It seems just starting `wolframscript` already takes multiple seconds, which is now the bottleneck. Not sure if anything can be done about that:
```sh
> time wolframscript -c 2+2
4
wolframscript -c 2+2  1.96s user 0.17s system 96% cpu 2.208 total
```
* Run the build script:
```sh
> time ./build.wls 
Build done.
./build.wls  12.06s user 0.66s system 107% cpu 11.842 total
```
* Change some …

Cache libSetReplace build

---

Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md

* Adds edits suggested by the internal Wolfram DQA team.
* In particular, changes defined terms in the definitions to **bold** and variables to *italic*.
* Thanks to *Taylor Birch* for these suggestions!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/517)

Confluence and Causal Invariance: DQA edits

---

build.wls
scripts/buildInit.wl

Use a temporary build directory, rather than the /Build subdir of the root dir. This is friendlier to IDEs, find-in-files, etc. This will have to be rebased if #518 lands to update the temporary directory used *there* as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/519)

Use a temporary build directory

---

Research/ConfluenceAndCausalInvariance/ConfluenceAndCausalInvariance.md

* Mentions classical sequential growth models for causal sets in Confluence and Causal Invariance note as examples of models where confluence is equivalent to causal invariance by construction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/527)

Confluence and Causal Invariance: Mention classical sequential growth models

---

.github/CONTRIBUTING.md
.gitignore

This change adds notebook files to the `.gitignore` list, for two reasons:
1. To make it much harder to deliberately or accidentally add notebooks to commits.
2. To make it friendlier to have a couple of "local notebooks" that are simply invisible to Git. (I use this for various purposes).
I've also added VSCode and Sublime workspace files, as well as files that contain the magic string "ignoreme.", which comes in handy when you want to 'stash' a single new file away easily without messing with git. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/530)

Ignore Mathematica notebooks

---

Kernel/globals.m
Kernel/init.m
Tests/buildData.wlt

* Fixes #508.
* Use `BeginPackage` and `Begin` to do proper context isolation to make loading GU safer, which we now do.
* Also include some useful sugar that isn't funky syntax which the previous override of `$DesugaringRules` unintentionally removed -- I will use this in a lot of code I write, including a pending PR (that will be resurrected soon!).
* Define the package global `$SetReplaceBaseDirectory`, which other PRs will end up using in various places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/520)

Load GeneralUtilities in Kernel/init.m, and add back some simple macro sugar

---

.circleci/config.yml

* Circle CI now saves the built libraries (including the metadata JSON) and the paclet file as artifacts.
* Note that the paclet file only has the Linux library. We will need to either cross-compile or run jobs on Mac and Windows to get a multi-platform paclet file, which is the goal.
* If we can achieve that, we will no longer need to rely on internal Wolfram infrastructure for building (which is inaccessible to external developers).
* Here they are: https://app.circleci.com/pipelines/github/maxitg/SetReplace/1292/workflows/bea84003-2279-43e9-8b84-87d013e6d532/jobs/1683/artifacts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/540)

Save build artifacts in CI

---

.circleci/config.yml
.github/CONTRIBUTING.md
lint.sh
scripts/git_hooks/pre-push
scripts/install_git_hooks.sh

* Closes #521.
* Implements a pre-push git hook that runs `./lint.sh` so that the linting issues can be fixed quickly before going to GitHub and CI.
* The hook can be installed by running `scripts/install_git_hooks.sh`.
* Adds a message to `./lint.sh` advising how to fix formatting errors.
* If `./lint.sh` fails on CI, it will now print a message advising to install the git hook.
* Note that the hooks live in the `.git/hooks` directory which is not version controlled. Each user has to install them manually. I assume this is done for security reasons so that users don't run the code they don't expect to run.
* First, install the hook:
```sh
> scripts/install_git_hooks.sh
Symlinking /Users/maxitg/git/SetReplace/scripts/git_hooks/pre-push to
/Users/maxitg/git/SetReplace/.git/hooks/pre-push …
```

Linter pre-push hook

---

.gitignore

* Adds the `build` directory used by default for CMake building purposes to `.gitignore`.
* It's not required to use this specific directory, but that's what `./libSetReplaceTest.sh` suggests to use.
* I believe it was not an issue previously because the temporary WL `Build` directory was in `.gitignore`, and `.gitignore` does not appear to be case sensitive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/544)

Add CMake build directory to gitignore

---

SetReplace.xcodeproj/project.pbxproj
libSetReplace/Match.cpp
libSetReplace/Parallelism.cpp
libSetReplace/Parallelism.hpp

* Fixes warnings generated when compiling with Xcode:
* There was some implicit type conversion.
* The macOS deployment target is updated to 11.0 (Big Sur).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/545)

Fix Xcode warnings

---

Kernel/WolframModelEvolutionObject.m
Tests/WolframModelEvolutionObject.wlt

* Closes #551.
* Prevents empty lists being treated as options in `WolframModelEvolutionObject` properties.
* Especially useful for potential properties where `{}` might be a valid optional argument like #528.
* Empty lists are no longer allowed:
```wl
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}]["FinalState", {}]
```
* Cherry-picking this into #528 now yields the expected result for passing an empty list as an argument:
```wl
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}]["FeatureAssociation", {}]
Out[] = <||>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/553)

Prevent empty lists being treated as options

---

libSetReplace/Match.cpp
libSetReplace/Parallelism.cpp
libSetReplace/Parallelism.hpp

* Changes non-standard integer types used in `Parallelism.*pp` to `int`.
* This is consistent with the [Google Style](https://google.github.io/styleguide/cppguide.html#Integer_Types).
* It also [prevents](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1355/workflows/7e8d28dc-3948-43ed-b1a8-b640fcba875a/jobs/1801) compile warnings [generated](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1354/workflows/6d9eb567-fe8c-48ec-95aa-c5f4301a827c/jobs/1800) by Visual Studio.
* Since the variables changed are related to the numbers of threads, they can never exceed the `int` range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/554)

Change non-standard types to int

---

.circleci/config.yml
performanceTest.wls

* `./performanceTest.wls` got broken after the introduction of in-place builds #529. This PR fixes it.
* As a result, `./performanceTest.wls` no longer installs any paclets, and tests everything in-place.
* Also added `./performanceTest.wls master @HEAD 2` to CI to prevent the script from breaking in the future, and to have an easy access to performance results.
* Having it in CI causes a ~30 seconds slowdown.
* I'm only running 2 tests instead of the default 5 to minimize that slowdown.
* CI won't fail if there is a slowdown. The purpose of this PR is to test the script itself, not its output.
* Check Performance Test in CI: https://app.circleci.com/pipelines/github/maxitg/SetReplace/1367/workflows/a36a3d08-0121-4b76-822b-457b8b680c1d/jobs/1825.
--- …

Fix performanceTest.wls for DevUtils

---

.circleci/config.yml

* Closes the Windows part of #371.
* Adds a CI build job on Windows.
* We have 25k monthly credits on Circle CI which should be plenty for building only (but won't be enough for full testing).
* The job uses CMake and builds a shared library (which we will need in the paclet).
* It already creates a DLL artifact which can be manually put directly into the paclet.
* Of course, the goal is to create the entire paclet, but before doing that, we need to create a metadata file (`libSetReplaceBuildInfo.json`), which will require computing the hash of the source code in bash.
* Check the [CI build](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1376/workflows/87374f0c-bb51-4b76-950d-2d8aa5ea61f4/jobs/1843), and, if you have Windows, try out the DLL file it generated in the Artifacts …

CI job: Windows

---

.circleci/config.yml
.gitignore
libSetReplaceTest.sh

* Stores results of *libSetReplace* tests in the new `TestResults` directory as JUnit XMLs.
* This allows Circle CI to pick up these results and display them in a nice way.
* The same can be done for Wolfram Language as well. We will need to produce the XMLs manually, but we can infer the format from the files generated by Googletest.
* This is what it looks like when tests [pass](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1379/workflows/31d17a1c-11c5-4d37-9b85-c165b2482a3e/jobs/1849/tests).
* And this is when they [fail](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1378/workflows/2bb65399-5864-4d71-b73a-2d8fff8f919a/jobs/1847/tests).
--- …

Googletest: Computable results

---

CMakeLists.txt

* Fixes a GTest deprecation warning, due to an out of date version.
Before fix:
```
$ cmake .. -DSET_REPLACE_ENABLE_ALLWARNINGS=ON -DBUILD_SHARED_LIBS=ON
-- SetReplace version: 0.3.0
-- SetReplace using CMAKE_CXX_STANDARD: 17
-- CMAKE_BUILD_TYPE: Release
-- SET_REPLACE_BUILD_TESTING: ON
-- SET_REPLACE_COMPILE_OPTIONS: -Wall;-Wextra;-Werror;-pedantic;-Wcast-align;-Wcast-qual;-Wctor-dtor-privacy;-Wdisabled-optimization;-Wformat=2;-Winit-self;-Wmissing-include-dirs;-Wold-style-cast;-Woverloaded-virtual;-Wredundant-decls;-Wshadow;-Wsign-promo;-Wswitch-default;-Wundef;-Wno-unused
CMake Deprecation Warning at build/_deps/googletest-src/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> …
```

Fix CMake Warning

---

.circleci/test.sh
libSetReplaceTest.sh
lint.sh
scripts/git_hooks/pre-push
scripts/install_git_hooks.sh

* Changes all shebangs to use `/usr/bin/env *`.
See [here](https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)#Portability) for shebang portability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/564)

Standardize Shebangs

---

.circleci/config.yml
scripts/buildLibraryResources.sh

* Useful for #552.
* Implements `buildLibraryResources.sh` script that builds correctly-formatted `LibraryResources` directory without using Wolfram Language including hashing the source files.
* Works on Linux, Mac, and Windows.
* Note that the hashes will not be the same as if produced by `./build.wls`. That is intentional since the hashes also include the sources of the build scripts.
* The hashes are not consistent between platforms as well because they contain `uname -sm` (similar to `./build.wls`).
* There is no `shasum` on Windows CI, so I'm using `certutil` instead, which is a bit hacky, but it works.
* Only 64-bit OS is supported because the intention is to only build the paclet for 64-bit OSs (like we did previously).
* On Mac:
```
> ./scripts/buildLibraryResources.sh
Using SHA …
```

CI: Build LibraryResources without Wolfram Language

---

.circleci/config.yml

* Closes #371.
* Adds macOS builds to the Circle CI workflow using the new `buildLibraryResources.sh` script.
* CI will fail until #561 is merged, the passing build with #561 cherry-picked is [here](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1426/workflows/67aff070-9e47-4215-9c55-481371310c38/jobs/2004/steps).
* I tried using [Homebrew](https://brew.sh) to install CMake which is much cleaner, but installing Homebrew itself takes [over 2 mins](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1423/workflows/73be1fa3-6e55-4c9d-87eb-afa49748f282/jobs/2000/steps), so I had to revert to manual installation like on Windows.
--- …

CI job: macOS

---

.circleci/config.yml
CMakeLists.txt
libSetReplace/Event.cpp
libSetReplace/Parallelism.cpp
libSetReplace/test/Parallelism_tests.cpp
libSetReplace/test/profile_tests.cpp

* Changes C++ CI image to use public alpine image rather than custom public one specifically for this repo.
* For some reason, cpplint is broken on previous CI image and was not catching errors. I fixed them in this PR. See [this failed build](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1434/workflows/6db31200-a23a-44e3-8ace-b0fb28b7f2c5/jobs/2037).
* Using this image makes it easier to install new tools on CI image for instance. There is no longer a need to edit a Dockerfile, build the image, then push anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/565)

Alpine Linux 64 CI

---

.circleci/config.yml
.github/CONTRIBUTING.md

* Closes #552.
* Renames CI jobs to explicitly say if they do building or testing.
* Copies the libraries from macos-build and windows-build, and puts them into the paclet created in wolfram-language-paclet-test before testing.
* As a result, the paclet-artifact from wolfram-language-paclet-test now contains libraries for all platforms.
* Also updates contributing guide accordingly to describe the new workflow and remove references to the internal build process.
* Here is [the workflow](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1454/workflows/91394b90-7214-439f-95f7-3e4aa617784b).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/568)

CI: Build multi-platform paclet

---

.circleci/test.sh
libSetReplaceTest.sh
lint.sh
scripts/install_git_hooks.sh

* Resolves #567.
* CI could silently fail in a lint step because `set +eo pipefail` in the CI script used to display an extra message in case of failure was not counteracted by `set -eo pipefail` in the lint script itself. (CI automatically sets `set -eo pipefail` to scripts if not manually disabled).
* This PR adds `set -eo pipefail` to all scripts to prevent this kind of weeds from happening.
* See an example of a fail build [here](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1457/workflows/48d322b2-0c86-4d0f-8d6c-695894d0cc9b/jobs/2144). Note that the hint about the hooks is still being printed at the end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace …

set -eo pipefail in all bash scripts

---

.circleci/config.yml

* Due to the ongoing change of Macs from x86 to ARM architecture, the archives with CMake releases are now named `-universal` instead of `-Darwin-x86_64`. As a result, macOS CI fails because it cannot find the macOS CMake in the most recent release.
* This fixes the name to search for.
* Perhaps, we should be using a specific version to prevent this from happening in the future. However, the architecture changes like this are rare, and it does save time to not have to update CMake manually, so perhaps we can leave it like this until/if the next issue arises.
* [CI job](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1501/workflows/52549d15-c635-4143-8650-667c088f390b/jobs/2363) now succeeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

CI: Fix CMake install script to use the new universal archive

---

lint.sh

This PR fixes two related issues:
* `./lint.sh` would silently exit (with exit code 1) if `clang-format` found formatting errors. This was caused `set -eo pipefail` which terminated the script after the first failure. Fixed with ` || :`
* Changed `printf`'s to `echo -e` because `printf` caused colors to stop working.
* Add a formatting error (for example, add a trailing space to `libSetReplace/Parallelism.hpp:37`).
* Run `./lint.sh`:
* As one can see, colors are now produced, the errors from `cpplint` are still generated, and the non-zero exit code is returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/577)

Fix early exit from clang-format in ./lint.sh

---

.circleci/config.yml
.circleci/test.sh

* Adds 4x parallelism to WL tests on CI
* Closes #448 
Currently, we do not have WL [test metadata](https://circleci.com/docs/2.0/collect-test-data/) compatible with CircleCI. Therefore, we can't use CircleCI's built-in [split-by timing](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timing-data) to distribute tests efficiently. This PR simply runs `matching` and `WolframModel` (which take the most time by far) each in separate executors, and splits the rest among the last two. 
In order to optimize this further, we could:
1. Distribute tests from `matching` and `WolframModel` into separate files.
2. Implement JUnit XML or Cucumber JSON test result reports for WL and enable `split-by timing`.
Parallel executors:
Test time is reduced by ~10 minutes (over ~2x …

Parallel WL Tests on CI

---

libSetReplace/Match.cpp
libSetReplace/SetReplace.cpp

* Adds some anonymous namespaces to force internal linkage
Library size is reduced:
`compareLibSize.sh`
```bash
#!/usr/bin/env bash
sizes=()
function getSize() {
rm -rf BuiltPaclets LibraryResources
git checkout "$1"
./build.wls
./install.wls
sizes+=("$(du -s LibraryResources | awk '{print $1;}')")
}
for tag in "$1" "$2"; do
getSize "$tag" &>/dev/null
done
echo -e "First: "${sizes[0]}"\nSecond: "${sizes[1]}"\nChange: $(printf "%s%%\n" "$(bc <<< "100 * "${sizes[1]}" / "${sizes[0]}"")")"
```
```bash
$ ./compareLibSize.sh master optimization/AnonymousNamespace
First: 243030
Second: 227678
Change: 93%
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/587)

Anonymous Namespaces

---

Kernel/setSubstitutionSystem$cpp.m
libSetReplace/SetReplace.cpp
libSetReplace/SetReplace.hpp

* Implements [managed expressions](https://reference.wolfram.com/language/LibraryLink/tutorial/InteractionWithWolframLanguage.html#353220453)
* Closes #574 
To verify release is actually working (and not just releasing at program exit):
```c++
void setManageInstance([[maybe_unused]] WolframLibraryData libData, mbool mode, mint id) {
std::string time = std::to_string(std::time(nullptr));
if (mode == 0) {
sets_.emplace(id, nullptr);
std::system((std::string("echo \"create ") + time + "\" >> /tmp/sr").c_str());
} else {
sets_.erase(id);
std::system((std::string("echo \"delete ") + time + "\" >> /tmp/sr").c_str());
}
}
```
```bash
$ ./test.wls eventDeduplication && cat /tmp/sr
create 1609878542
delete 1609878542
create 1609878542
delete 1609878542
create 1609878542
delete 1609878542
... …
```

Managed Expressions

---

Kernel/setSubstitutionSystem$cpp.m

* Passes args to libSetReplace using [`"Constant"`](https://reference.wolfram.com/language/LibraryLink/tutorial/InteractionWithWolframLanguage.html#97446640), since we don't modify the MTensor on C++ side. This prevents a copy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/589)

Constant LibraryLink Arguments

---

.github/CONTRIBUTING.md

* The "code style" links in the contributing page were not working: there was a "# Style" section but no "# Code Style".
* The section might be intenionally be named "Style", in which case I should change "#code-style" to "#style".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/593)

Changing section name "# Style" to "# Code Style".

---

.circleci/config.yml
performanceTest.wls

* Closes #573.
* Allows using `HEAD` as an argument to `./performanceTest.wls`.
* Fixes CI to use `HEAD` instead of (an incorrect) `@HEAD`.
* `./performanceTest.wls` was broken on CI because it fails with `HEAD` and silently fails with `@HEAD` by running the tests on the same branch again (so the performance report is always at zero).
* Test `HEAD` against `master`:
```console
$ ./performanceTest.wls master HEAD 2
Testing master
Testing 286a74794bb15a89addc2c697a7d66124b10de0e
Single-input rule                       -5.5 ± 0.6 %
Medium rule                             -1.2 ± 2.7 %
Sequential rule                         -0.2 ± 0.6 %
Large rule                              -1.9 ± 1.2 %
Exponential-match-count rule            -1. ± 4. %
CA emulator                             0. ± 10. %
``` …

Allows using HEAD in performanceTest.wls and fixes it on CI

---

.github/CONTRIBUTING.md
README.md
Research/LocalMultiwaySystem/LocalMultiwaySystem.md

* Removes references to unreliable sources such as [wolframphysics.org](https://www.wolframphysics.org) which has known errors that have not been fixed for a substantial amount of time.
* Also removes the note about reporting Wolfram Physics issues elsewhere as without the link to [wolframphysics.org](https://www.wolframphysics.org) on the main repo page, it is no longer necessary.
* `WolframPhysicsProjectStyleData` will be renamed to `SetReplaceStyleData` in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/607)

Remove unreliable references

---

.circleci/config.yml

* macOS and Windows CI was failing again to download CMake due to the change of name from `*macos-universal*` to `*Darwin*`.
* Since this is likely to happen again (they need to support ARM Macs), I'm fixing the version to 3.18.6 to prevent the CI from failing now and in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/614)

Fix CMake download on CI to version 3.18.6

---

Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md

* Fixes broken links in `Feature*` functions.
* The links were split into multiple lines which caused them to not render on GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/615)

Fix broken links in Feature* functions

---

CMakeLists.txt

* v1.10.x of googletest has not been updated for a while, and is now triggering a CMake deprecation warning.
* This gets googletest from master to avoid that.
* Before:
```console
$ cmake .. -DSET_REPLACE_BUILD_TESTING=ON 
-- SetReplace version: 0.3.0
-- SetReplace using CMAKE_CXX_STANDARD: 17
-- CMAKE_BUILD_TYPE: Debug
-- SET_REPLACE_BUILD_TESTING: ON
-- SET_REPLACE_COMPILE_OPTIONS: 
CMake Deprecation Warning at build/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C …
```

Obtain googletest from master

---

Kernel/A1$typeSystem.m

* Labels for types that are lists (e.g., `{MultisetSubstitutionSystem, 0}`) don't currently show correctly due to `Graph` interpreting `MultisetSubstitutionSystem` and `0` as separate labels and plotting them on top of each other.
* This PR fixes that by converting labels to strings.
* Declare a type:
```wl
SetReplace`PackageScope`declareTypeTranslation[Identity, {String, 0}, {Integer, 0}];
Unprotect[$SetReplaceTypes];
Unprotect[$SetReplaceProperties];
Unprotect[$SetReplaceTypeGraph];
SetReplace`PackageScope`initializeTypeSystem[];
```
* Show a type graph which is now rendered correctly:
```wl
In[] := $SetReplaceTypeGraph
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setrepla …

Fix labels for list-types in $SetReplaceTypeGraph

---

.circleci/config.yml
PacletInfo.m
README.md

* Wolfram Language 12.2 was released a while ago, and it has some useful features (e.g., for arguments checking), so I think it's a good time to start using it.
* If there are any objections, let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/627)

Update minimum Wolfram Language version to 12.2.0

---

test.wls

* `test.wls` fails the test file parsing if there are trailing/leading comments.
* The reason is that `ToExpression[_, InputForm, Hold]` would pass multiple arguments to `Hold` in case multiple expressions were read from the file. And comments were treated as `Null` expressions.
* I'm now manually deleting `Null` expressions, which should solve it unless there actually are multiple non-`Null` expressions.
* Any edge cases I might be missing?
* Add some comments on new lines to the end of a test file, e.g., `SetReplace.wlt`:
```wl
(* sdfsdfsdf *)
(* sdfsdfsdf *)
```
* Now, run the tests (ignore the macOS front-end error):
```console
$ ./test.wls SetReplace
Loading SetReplace from /Users/maxitg/git/SetReplace/Kernel/init.m
SetReplace                              [ok]
2021-03-25 13:26:50.514 …
```

Allow trailing comments in test files

---

Kernel/MultisetToWolframModelEvolutionObject.m
Tests/MultisetToWolframModelEvolutionObject.wlt

* Due to a typo in `"Complete"` termination reason, conversion to `WolframModelEvolutionObject` was failing.
* This is now fixed.
* The case that did not previously work:
```wl
In[] := SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}] @
GenerateMultihistory[
MultisetSubstitutionSystem[{a_, b_} :> {a + b}],
{"MaxGeneration" -> 1, "MaxEventInputs" -> 2},
None,
EventOrderingFunctions[MultisetSubstitutionSystem],
{}] @
{1, 2, 3}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/633)

Fix Multiset to WolframModelEvolutionObject for "Complete" termination reason

---

Kernel/A1$GenerateMultihistory.m
Kernel/MultisetSubstitutionSystem.m
Tests/MultisetSubstitutionSystem.wlt
Tests/hypergraphMatching.wlt

* `"SortedInputExpressions"` and `"UnsortedInputExpressions"` weren't good names for ordering functions because, using the word "expression" instead of "token", they are specific to the multiset system, and it's better if they are not since they can then have shared documentation.
* This PR renames them to `"SortedInputTokenIndices"` and `"InputTokenIndices"`.
* `"SortedInputTokenIndices"` might be harder to understand at first than `"OldestToken"`, but I think it's better because it explains exactly what it is whereas `"OldestToken"` might be interpreted in different ways. `"OldestToken"` is actually closer to `"MinInputTokenIndex"`, which we don't have yet, but we might in the future.
* Not sure if `"Unsorted"` is necessary in `"InputTokenIndices"`, so I removed it.
* New names:
```wl …
```

New names for MultisetSubstitutionSystem ordering functions

---

Kernel/A1$GenerateMultihistory.m
Kernel/MultisetSubstitutionSystem.m
Tests/MultisetSubstitutionSystem.wlt
Tests/hypergraphMatching.wlt
performanceTest.wls

* Closes #637.
* Left-hand sides of rules such as `{a__, b__}` will now be matched multiple times even if the ordered sequence of tokens is the same (e.g., as `{{a} -> {1}, {b} -> {2, 3}}` and `{{a} -> {1, 2}, {b} -> {3}}`).
* This was done by allowing the same sequence of tokens to be matched multiple times (how many times is computed during the matching step).
* This required adding another ordering function, `"InstantiationIndex"`, which controls which of the instantiations will be used first. (There is still no customization of the ordering at the moment.)
* The example from the issue can now generate both matches:
```wl
In[] := #["ExpressionsEventsGraph", VertexLabels -> Automatic] &@
SetReplaceTypeConvert[{WolframModelEvolutionObject, 2}]@
GenerateMultihistory[ …
```

MultisetSubstitutionSystem: allow patterns like {a__, b__} to be matched multiple times

---

Kernel/setSubstitutionSystem$cpp.m
libSetReplace/WolframLanguageAPI.cpp

* Closes #641.
* We are currently passing 64-bit ints for disabled step specs, and an unsigned 32-bit for the seed initialization. WL LibraryLink does not support that on 32-bit platforms, so any calls to `libSetReplace` would fail.
* This PR changes it to pass -1 and 31-bit ints instead, which should fix that issue.
* Someone with a 32-bit system needs to confirm there is nothing else here I'm missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/648)

Avoid passing 64-bit ints through LibraryLink

---

.circleci/config.yml
CMakeLists.txt
PacletInfo.m
scripts/buildLibraryResources.sh

* Compiles the Mac library for both arm64 and x86_64 to enable Apple Silicon support.
To check an architecture and mark the checkbox, evaluate:
```wl
PacletUninstall["SetReplace"];
Quit;
PacletInstall["path_to_built_paclet_in_CI"];
<< SetReplace`;
WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}, 4, "FinalStatePlot", Method -> "LowLevel"]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/651)

Apple ARM support

---

libSetReplace/HypergraphMatcher.cpp
libSetReplace/test/HypergraphSubstitutionSystem_test.cpp

* Resolves #642.
* Fixes seeding in multi-rule `WolframModel`.
* Adding matches for different rules in parallel caused non-determinism, which broke consistency with specified seeds.
* In the case of multiple rules, the matches are now added to intermediate storage (similar to `EventDeduplication::SameInputSetIsomorphicOutputs`), and then sorted before being added to the main storage.
```wl
In[] := Counts @ Table[
BlockRandom[
WolframModel[<|"PatternRules" -> {{{1, 2}} -> {}, {{2, 3}} -> {}}|>,
{{1, 2}, {2, 3}},
<|"MaxEvents" -> 1|>,
"EventOrderingFunction" -> "Random"]["FinalState"],
RandomSeeding -> 123],
100]
Out[] = <|{{2, 3}} -> 100|>
```
--- …

Fix seeding for multi-rule systems

---

.circleci/config.yml
DevUtils/GitLink.m
DevUtils/PackSetReplace.m
Kernel/convexHullPolygon.m
PacletInfo.m
README.md
install.wls

* Updates the minimum required WL version to 12.3.
* Removes WL prerelease tests.
* Removes unnecessary backward-compatibility code.
* This allows us to use WL 12.3 features without any restrictions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/652)

Wolfram Language 12.3

---

.circleci/config.yml
lint.sh
scripts/checkLineWidth.sh

* Removes unnecessary `\` at the ends of lines in `lint.sh`.
* Removes unnecessary self-assignment in `checkLineWidth.sh`.
* `./lint.sh` no longer generates errors:
```console
$ ./lint.sh
$
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/654)

Fix linting with new tool versions

---

DevUtils/BuildLibSetReplace.m

* Changes ``System`Dump`LibraryExtension`` to ``Internal`DynamicLibraryExtension`` due to impending deprecation.
* Remove cache:
```console
$ rm -rf LibraryResources
```
* Build *libSetReplace*:
```wl
In[] := BuildLibSetReplace[]
Out[] = <|"LibraryPath" -> "/Users/maxitg/git/SetReplace/LibraryResources/MacOSX-x86-64/libSetReplace-165zdmc3jmt79.dylib", 
"LibraryFileName" -> "libSetReplace-165zdmc3jmt79.dylib", "LibraryBuildTime" -> {2021, 6, 13, 17, 31, 13}, 
"LibrarySourceHash" -> "165zdmc3jmt79", "FromCache" -> False|>
```
* The library extension is correct (at least on a Mac).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/655)

System`Dump`LibraryExtension -> Internal`DynamicLibraryExtension

---

performanceTest.wls

* Due to a weed in Wolfram Language, `MeanAround` sometimes returns a single number instead of `Around`:
```wl
In[] := MeanAround[{1, 1}]
Out[] = 1
```
* This [sometimes breaks](https://app.circleci.com/pipelines/github/maxitg/SetReplace/2018/workflows/77fc408b-d297-4efd-a01c-517ad52ccb54/jobs/4997) `./performanceTest.wls`, which assumes `Around` objects.
* This PR implements a workaround for this case.
* This case happens rarely, but manually assigning `magnitude = 1` in `differenceString` does work:
```console
$ ./performanceTest.wls master HEAD 2
Testing 811551cb72de921652430003f56fcf25e4a8f185
Testing 19264e2884d6d3cc6831c1fcce2941225f7d217c
Single-input rule                       1 ± 0 %
Medium rule                             1 ± 0 %
Sequential rule                         1 ± 0 % …
```

Fix for disappearing Around

---

Kernel/A0$style.m
Kernel/Multihistory.m
Kernel/WolframModelEvolutionObject.m

* Renames outdated style names such as `$causalGraphVertexStyle` to modern TEG names such as `$eventVertexStyle`.
* Does not change names used in `SetReplaceStyleData` to preserve backward compatibility for now.
* I only changed the TEG-related style names for now, as I need them for the `TokenEventGraph` property.
* No functionality is affected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/667)

Rename causal graph styles to TEG styles

---

DevUtils/BuildLibSetReplace.m

I noticed that the `WolframModel` evolutions were taking an extremely long time to evaluate. I also noticed that the fairly straightforward evaluation of `RandomWolframModel` was completely locking up my computer. After looking at the dylib produced by `DevUtils/BuildLibSetReplace.m` I noticed that it was not being build with compiler optimizations, so I added them.
Fairly simple, low risk change here assuming we trust the compiler. Should yield more performance for all who want to use this library. :)
Run `./install.wls` to build with compiler optimizations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/668)

Enable compiler optimizations for WolframScript builds.

---

Kernel/GeneralizedGridGraph.m
Kernel/HypergraphPlot.m
Kernel/RulePlot.m
Kernel/WolframModel.m
Kernel/WolframModelEvolutionObject.m
Kernel/argumentsChecking.m
Kernel/setSubstitutionSystem.m
Tests/GeneralizedGridGraph.wlt
Tests/RulePlot.wlt
Tests/WolframModel.wlt
Tests/WolframModelEvolutionObject.wlt

* Functions in `argumentsChecking.m` now throw exceptions instead of printing messages.
* `HypergraphPlot`, `RulePlot`, `WolframModel`, `WolframModelEvolutionObject` and `GeneralizedGridGraph` were updated to use `messages.m` and exceptions.
* The main goal here is to change `knownOptionsQ` and `supportedOptionQ` to throw exceptions, as they are useful for implementing properties.
* The only change to functionality is that `WolframModelEvolutionObject` plotting functions now correctly print messages from `WolframModelEvolutonObject` instead of `HypergraphPlot`:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/666)

Throw exceptions in argumentsChecking, HypergraphPlot, WolframModel and GeneralizedGridGraph

---

.circleci/config.yml
.gitignore
CMakeLists.txt

* Introduce the minimal set of changes to make CI pass again for the first time since the last successful build in 2021.
* Update some of the pinned dependencies:
* macOS executor 12.2.0 -> 16.2.0;
* CMake 3.18.6 -> 3.31.5;
* alpine (on x86_64) 3.13.5 -> 3.21.2.
* Pin some dependencies to avoid introducing compatibility issues:
* cpplint to 1.5.5;
* markdown-cli to 0.37.0.
* Update the googletest branch `master` -> `main`.
* Use the official `wolframresearch/wolframengine` Docker image instead of the custom one.
* Increase the timeout for Wolfram Language tests 10 min -> 20 min.
* cpplint is pinned to 1.5.5 because newer versions require headers to be in a directory by default. The refactor will be done in a separate PR.
* `markdownlint-cli` is pinned to 0.37.0 because newer versions …

Fix and pin dependencies to unblock CI

---

.github/CONTRIBUTING.md
README.md

* Add alt text to all images in the main README and CONTRIBUTING.md.
* This is needed to update markdownlint-cli to the latest version 0.44.0 without disabling rules.
README is now more readable without images:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/SetReplace/674)

Add alt text to README.md and CONTRIBUTING.md

---

.circleci/config.yml
scripts/activateWolframScript.sh

* Try WolframScript activation up to 3 times before failing.
* WolframScript activation [keeps failing](https://app.circleci.com/pipelines/github/maxitg/SetReplace/2125/workflows/a937820e-d49c-4bfe-b3fe-21fe60fb4aec/jobs/5523) intermittently because it "could not connect to https://www.wolframcloud.com/". We cannot avoid doing it, however, we can decrease the probability of failure by retrying a few times.
* Passing wrong `WOLFRAM_ID` and `WOLFRAM_PASSWORD`:
```console
$ export WOLFRAM_ID="test@test.test"
$ export WOLFRAM_PASSWORD="123"
$ ./scripts/activateWolframScript.sh 
Attempt 1...
Incorrect username or password
Activation failed on attempt 1. Retrying...
Attempt 2...
Incorrect username or password
Activation failed on attempt 2. Retrying...
Attempt 3...
Incorrect username or …
```

Retry WolframScript activation

---

.circleci/config.yml
test.wls

* Add a test counter to indicate progress while the tests are running.
* Reset the timeout for no terminal output to 10 minutes.
* CircleCI times out if there is no terminal output for 10 minutes by default and for 20 minutes given our current config.
* We could extend the timeout further, but it's better to show actual progress. It's also useful to get an estimate for how long one has to wait for the tests to be done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/SetReplace/678)

Show test counter in test.wls

---

.circleci/config.yml
CPPLINT.cfg
libSetReplace/test/HypergraphSubstitutionSystem_test.cpp

* Update cpplint 1.5.5 -> 2.0.0.
* Add missing C++ Standard Library includes.
* Disable `build/include_subdir` as we don't currently have subdirectories in the C++ code.
* Disable `whitespace/indent_namespace` due to https://github.com/cpplint/cpplint/issues/293.
* I'm keeping the version pinned so that builds are reproducible.
* The plan is to switch to [Trunk](https://trunk.io/code-quality) in the future to make local linting reproducible as well.
```console
$ cpplint libSetReplace/*.cpp libSetReplace/*.hpp libSetReplace/test/*.cpp
Done processing libSetReplace/AtomsIndex.cpp
Done processing libSetReplace/AtomsIndex.hpp
Done processing libSetReplace/HypergraphMatcher.cpp
Done processing libSetReplace/HypergraphMatcher.hpp
Done processing libSetReplace/HypergraphSubstitutionSystem.cpp …
```

cpplint 2.0.0
