maxitg/SetReplace

- SetReplace.wl
* Closes https://github.com/maxitg/SetReplace/issues/4.
* Makes arrowheads have the same sizes as in Graph.
* Also adjusts the end-point of the arrows, so that they are not obscured by vertices.
* Run `HypergraphPlot[Table[Table[RandomInteger[{1, 2000}], 10], 50]]`
* Before
* After
> Correct arrowheads in HypergraphPlot

- README.md
* Updated README with a usage example.
> Update README with a usage example.

- PacletInfo.m
- SetReplace.wl
- SetReplace/SetReplace/Match.cpp
- SetReplace/SetReplace/Set.cpp
- SetReplace/SetReplace/SetReplace.cpp
- build.wls
* Closes #26.
* Adds support for Linux and Windows.
* Replaces Xcode compilation with compilation using ``CCompilerDriver` `` in Wolfram Language.
* Run `./build.wls` on all macOS (done), Linux (done) and Windows (done).
* Install the created paclet.
* Evaluate `SetReplace[{{0}}, {{x_}} :> {{x}}, Method -> "C++"]`, if no warnings are produced, C++ code was successfully compiled.
> Cross platform build

- SetReplace.wlt
* Adds a comment explaining timing check in Abort test.
> Comment Abort test timing

- PacletInfo.m
* Bumps version number to 0.2.
* This is done every time after release to distinguish the previous release version from the current prerelease development version.
> Version 0.2

- SetReplace/SetReplace.xcodeproj/project.pbxproj
- SetReplace/libSetReplace/Event.hpp
- SetReplace/libSetReplace/Expression.cpp
- SetReplace/libSetReplace/Expression.hpp
- SetReplace/libSetReplace/IDTypes.hpp
- SetReplace/libSetReplace/Match.cpp
- SetReplace/libSetReplace/Match.hpp
- SetReplace/libSetReplace/Rule.hpp
- SetReplace/libSetReplace/Set.cpp
- SetReplace/libSetReplace/Set.hpp
- SetReplace/libSetReplace/SetReplace.cpp
- build.wls
* Closes #14 .
* Refactors C++ code to make it more modular and easier to read.
* In particular, moves all rule-input-matching logic into `Match.cpp`.
* Adds doxygen comments to all `.h` files.
* Adds comments throughout the implementation.
* `./build.sh && ./install.sh && ./test.sh`.
* Check all tests pass.
```
FromAnonymousRules.wlt                  [ok]
HypergraphPlot.wlt                      [ok]
meta.wlt                                [ok]
SetReplaceAll.wlt                       [ok]
SetReplaceFixedPointList.wlt            [ok]
SetReplaceFixedPoint.wlt                [ok]
SetReplaceList.wlt                      [ok]
SetReplace.wlt                          [ok]
Report file: /private/var/folders/0k/c8syr9b51575_ndkvh564l840000gn/T/m000001630551/testReport.nb
``` …
> C++ code refactor

- SetReplace/libSetReplace/Expression.hpp
* Adds necessary includes to fix compilation on Linux.
* On Linux: `./build.wls && ./install.wls && ./test.wls`.
> Fix Linux compilation

- .fire.yml
- SetReplace/RulePlot.wlt
- test.wls
* Adds a Fire CI configuration YAML.
* Removes unreliable `RulePlot` tests that required `Rasterize`, and therefore, a front end to work.
* Changes test output formatting to look better in GitHub UI.
* Check the green mark saying "All checks have passed" at the bottom of the page. No need to manually run tests anymore.
> Configure Fire CI

- install.wls
* In the install script, change the name inference from the manual to supported method.
* Check CI can install the paclet.
> Fix obtaining expected paclet filename.

- SetReplace/WolframModelEvolutionObject.m
- SetReplace/WolframModelEvolutionObject.wlt
* Adds accessors to evolution object properties: `"CreatorEvents"`, `"DestroyerEvents"`, `"AllExpressions"`, and `"ExpressionGenerations"`.
* Show creating, destroying events, and a generation for all expressions produced during an evolution:
```
In[] := # -> {##2} & @@@ 
Transpose@
WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}, 
3, {"AllExpressions", "CreatorEvents", "DestroyerEvents", 
"ExpressionGenerations"}]
```
```
Out[] = {{1, 1} -> {0, 1, 0}, {1, 2} -> {1, 2, 1}, {1, 2} -> {1, 3, 1}, {2, 
1} -> {1, 4, 1}, {1, 3} -> {2, 5, 2}, {1, 3} -> {2, 6, 2}, {3, 
2} -> {2, 7, 2}, {1, 4} -> {3, 8, 2}, {1, 4} -> {3, 9, 2}, {4, 
2} -> {3, 10, 2}, {2, 5} -> {4, 11, 2}, {2, 5} -> {4, 12, 2}, {5, 
1} -> {4, 13, 2}, {1, 6} -> {5, \[Infinity], 3}, {1, 
6} -> {5, \[Infinity], 3}, {6, 3} …
```
> Evolution accessors

- SetReplace/WolframModel.wlt
- SetReplace/WolframModelEvolutionObject.m
- SetReplace/libSetReplace/Set.cpp
- SetReplace/libSetReplace/Set.hpp
- SetReplace/libSetReplace/SetReplace.cpp
- SetReplace/libSetReplace/SetReplace.hpp
- SetReplace/setSubstitutionSystem$cpp.m
- SetReplace/setSubstitutionSystem$wl.m
- SetReplace/setSubstitutionSystem.m
* Adds property `"TerminationReason"` of `WolframModel` and `WolframModelEvolutionObject`, which returns the event that caused the evolution to stop.
* Possible values are the same as step limiters (`"MaxEvents"`, `"MaxGenerations"`, `"MaxVertices"`, `"MaxEdges"`, `"MaxVertexDegree"`), in addition to `"FixedPoint"` (there are no more matches to use for events), `"TimeConstraint"` and `"Aborted"` (for manual abort from Mathematica UI).
* The termination reason is also displayed in the expanded view of evolution object boxes.
* Evolve a system for `10` generations, and check that it terminated due to that generations limit:
```
In[] := WolframModel[{{1, 2}, {1, 3}} -> {{1, 2}, {1, 3}, {3, 4}}, {{1, 
1}, {1, 1}}, 10]
```
* If we add a constraint for the number of events, that could trigger …
> Termination reason

- build.wls
- install.wls
- scripts/buildInit.wl
- scripts/buildLibSetReplace.wls
- scripts/packPaclet.wls
- scripts/re_build_SetReplace.xml
- scripts/version.wl
* Adds build scripts for Wolfram internal paclet repository.
* `build.wls` now automatically assigns a minor version based on the number of commits from the specified checkpoint to the merge base with master.
> Internal build

- SetReplace/PacletInfo.m
* Changes `PacletInfo.m` to mention Wolfram Physics Project.
* Fixes requires Mathematica version.
> Physics Project paclet info

- Kernel/style.m
Updated style.m to include MultiwaySystem-specific graph styles (StatesGraph, EvolutionCausalGraph and BranchialGraph).
> Multiway styles

- README.md
* Adds references to Physics Project launch materials.
* @sskini2, could you check if the URLs are correct? Especially to Jonathan's papers?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/303)
> Link to launch materials

- .github/CONTRIBUTING.md
- README.md
* Corrected some grammar and spelling mistakes.
* Reworded awkward phrasing to be more coherent.
* No code changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/326)
> Readme and Contributing grammar/spelling corrections

- install.wls
- scripts/buildInit.wl
- test.wls
* Resolves #434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/439)
> Build with AbsoluteFileName

- Research/LocalMultiwaySystem/LocalMultiwaySystem.md
* Adds a few more edits spotted by the internal Wolfram DQA team.
* Thanks to *Taylor Birch* for spotting these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/482)
> More edits to Local Multiway System

- Research/LocalMultiwaySystem/LocalMultiwaySystem.md
* One closing curly brace was missing and was added here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/491)
> Local Multiway System: add missing curly brace

- Kernel/setSubstitutionSystem$cpp.m
Try to find the libSetReplace in the same part of the filesystem that the source was loaded from. If that fails, look for a possible Build directory that contains a staged build to use. If that fails, give up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/518)
> Improve libSetReplace loading

- .github/CONTRIBUTING.md
- scripts/git_hooks/pre-commit
- scripts/install_git_hooks.sh
* Adds pre-commit hook to format staged C++ files before committing
* Adds option to hook install script to only install one hook
* Updates documentation on how to use hook install script and how to uninstall hooks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/550)
> Format pre-commit hook

- .circleci/config.yml
* Adds 32-bit CI step for libSetReplace (i386 AlpineLinux)
* Related to #371 
GTest passes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/560)
> Linux32 CI

- .circleci/config.yml
- .circleci/test.sh
* Enables a job on CI that tests compatibility with Wolfram Language 12.3.
* I want to check that nothing will break once it is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/setreplace/628)
> Test Wolfram Language 12.3
